// SPDX-License-Identifier: GPL-3.0-or-later
// S-Log MetaRaw develop math, shared by the CPU path (C++) and the Metal kernel
// (this file is embedded as source text in the kernel). Reference implementation
// for the tests: tests/develop_model.py.
// GENERATED by tools/build_math.py from DevelopMath.h.in - do not edit DevelopMath.h.
#ifndef SONYMETA_DEVELOP_MATH_H
#define SONYMETA_DEVELOP_MATH_H

#ifdef __METAL_VERSION__
#define SM_FN inline
#define SM_CONST constant
#define SM_CPTR constant float*
#define SM_POW pow
#define SM_LOG2 log2
#define SM_LOG10 log10
#define SM_EXP2 exp2
#define SM_MAX fmax
#define SM_MIN fmin
#else
#include <math.h>
#define SM_FN static inline
#define SM_CONST static const
#define SM_CPTR const float*
#define SM_POW powf
#define SM_LOG2 log2f
#define SM_LOG10 log10f
#define SM_EXP2 exp2f
#define SM_MAX fmaxf
#define SM_MIN fminf
#endif

struct SMf3 { float x; float y; float z; };

SM_FN SMf3 smf3(float x, float y, float z) { SMf3 r; r.x = x; r.y = y; r.z = z; return r; }
SM_FN float sm_clamp(float v, float a, float b) { return SM_MIN(SM_MAX(v, a), b); }

// All-scalar layout so it is identical in C++ and Metal.
struct DevelopParams {
    int bypass;        // 1 = pass the image through untouched
    int convert;       // 1 = Color Space / Gamma differ from the node space
    int nodeSpace;     // gamut code of the image entering the node
    int nodeGamma;     // transfer code of the image entering the node
    int outSpace;
    int outGamma;
    float expo;        // chosen EI / EI at capture
    float ratioL;      // Bradford LMS white ratios (as-shot white / chosen white)
    float ratioM;
    float ratioS;
    float norm;        // keeps the luminance of D65 unchanged by the WB move
    float shadows;
    float highlights;
    float contrast;
    float saturation;
    float boost;
    int levelFix;      // 1 = rescale the code values before the log decode
    int levelSpace;    // gamut of the domain the rescale happens in (the camera's)
    int levelGamma;    // transfer of that domain (the camera's log curve)
    float levelGain;   // code value -> code value, affine
    float levelOffset;
    int fcMode;        // false colour: 0 off, 1 exposure, 2 temperature, 3 tint
    float fcU;         // CIE 1960 uv of the working space white (D65)
    float fcV;
    float fcKu;        // uv deviation -> Kelvin of slider travel: row 0 of the
    float fcKv;        // inverted slider response measured in buildParams
    float fcTu;        // uv deviation -> tint units: row 1 of the same inverse
    float fcTv;
    float chromaRecover;  // -1..1: colour back into recovered highlights, chroma
                          // noise out of lifted shadows. 0 = the film-natural default
};

// ---------------------------------------------------------------- transfer functions
// codes: 0 DaVinci Intermediate, 1 Linear, 2 Gamma 2.2, 3 Gamma 2.4, 4 Gamma 2.6,
//        5 Rec.709 (BT.709 OETF), 6 sRGB, 7 SLog, 8 SLog2, 9 SLog3, 10 ACEScct

SM_FN float sm_spow(float x, float p) { return x < 0.0f ? -SM_POW(-x, p) : SM_POW(x, p); }

SM_FN float sm_slog_enc(float r) {  // Sony S-Log core, r = reflection / 0.9 (Sony papers)
    float y = r >= 0.0f ? 0.432699f * SM_LOG10(r + 0.037584f) + 0.616596f + 0.03f
                        : r * 5.0f + 0.030001222851889303f;
    return (y * 876.0f + 64.0f) / 1023.0f;
}
SM_FN float sm_slog_dec(float x) {
    float y = (x * 1023.0f - 64.0f) / 876.0f;
    return y >= 0.030001222851889303f ? SM_POW(10.0f, (y - 0.616596f - 0.03f) / 0.432699f) - 0.037584f
                                      : (y - 0.030001222851889303f) / 5.0f;
}

SM_FN float sm_encode(float y, int g) {
    if (g == 0) return y <= 0.00262409f ? y * 10.44426855f : (SM_LOG2(y + 0.0075f) + 7.0f) * 0.07329248f;
    if (g == 2) return sm_spow(y, 1.0f / 2.2f);
    if (g == 3) return sm_spow(y, 1.0f / 2.4f);
    if (g == 4) return sm_spow(y, 1.0f / 2.6f);
    if (g == 5) return y < 0.018f ? 4.5f * y : 1.099f * SM_POW(y, 0.45f) - 0.099f;
    if (g == 6) return y <= 0.0031308f ? 12.92f * y : 1.055f * SM_POW(y, 1.0f / 2.4f) - 0.055f;
    if (g == 7) return sm_slog_enc(y / 0.9f);
    if (g == 8) return sm_slog_enc(y * 155.0f / 219.0f / 0.9f);
    if (g == 9) return y >= 0.01125f ? (420.0f + SM_LOG10((y + 0.01f) / 0.19f) * 261.5f) / 1023.0f
                                     : (y * (171.2102946929f - 95.0f) / 0.01125f + 95.0f) / 1023.0f;
    if (g == 10) return y <= 0.0078125f ? 10.5402377416545f * y + 0.0729055341958355f : (SM_LOG2(y) + 9.72f) / 17.52f;
    return y;
}
SM_FN float sm_decode(float x, int g) {
    if (g == 0) return x <= 0.02740668f ? x / 10.44426855f : SM_EXP2(x / 0.07329248f - 7.0f) - 0.0075f;
    if (g == 2) return sm_spow(x, 2.2f);
    if (g == 3) return sm_spow(x, 2.4f);
    if (g == 4) return sm_spow(x, 2.6f);
    if (g == 5) return x < 0.081f ? x / 4.5f : SM_POW((x + 0.099f) / 1.099f, 1.0f / 0.45f);
    if (g == 6) return x <= 0.04045f ? x / 12.92f : SM_POW((x + 0.055f) / 1.055f, 2.4f);
    if (g == 7) return sm_slog_dec(x) * 0.9f;
    if (g == 8) return sm_slog_dec(x) * 0.9f * 219.0f / 155.0f;
    if (g == 9) return x >= 171.2102946929f / 1023.0f ? SM_POW(10.0f, (x * 1023.0f - 420.0f) / 261.5f) * 0.19f - 0.01f
                                                      : (x * 1023.0f - 95.0f) * 0.01125f / (171.2102946929f - 95.0f);
    if (g == 10) return x <= 0.155251141552511f ? (x - 0.0729055341958355f) / 10.5402377416545f : SM_EXP2(x * 17.52f - 9.72f);
    return x;
}

// ---------------------------------------------------------------- matrices (adapted to D65)
// codes: 0 DaVinci WG, 1 Rec.709, 2 Rec.2020, 3 P3 D65, 4 P3 D60, 5 P3 DCI, 6 S-Gamut,
//        7 S-Gamut3, 8 S-Gamut3.Cine, 9 ACES AP0, 10 ACES AP1

SM_CONST float SM_RGB_TO_XYZ[99] = {
    0.700622392f, 0.148774815f, 0.10105872f, 0.274118511f, 0.873631896f, -0.147750407f, -0.098962913f, -0.137895325f, 1.325915989f,  // 0 DWG
    0.412390799f, 0.357584339f, 0.180480788f, 0.212639006f, 0.715168679f, 0.072192315f, 0.019330819f, 0.11919478f, 0.950532152f,  // 1 709
    0.636958048f, 0.144616904f, 0.168880975f, 0.262700212f, 0.677998072f, 0.059301716f, 0.0f, 0.028072693f, 1.060985058f,  // 2 2020
    0.486570949f, 0.265667693f, 0.198217285f, 0.228974564f, 0.691738522f, 0.079286914f, 0.0f, 0.045113382f, 1.043944369f,  // 3 P3D65
    0.497045658f, 0.257803898f, 0.195606372f, 0.234228848f, 0.688681965f, 0.077089187f, 0.000340577f, 0.04591839f, 1.042798784f,  // 4 P3D60
    0.459251655f, 0.295791788f, 0.195412485f, 0.215150512f, 0.709133637f, 0.075715851f, 0.000272006f, 0.046939514f, 1.041846231f,  // 5 P3DCI
    0.706482713f, 0.12880105f, 0.115172164f, 0.270979671f, 0.786606411f, -0.057586082f, -0.009677845f, 0.004600037f, 1.094135559f,  // 6 SG
    0.706482713f, 0.12880105f, 0.115172164f, 0.270979671f, 0.786606411f, -0.057586082f, -0.009677845f, 0.004600037f, 1.094135559f,  // 7 SG3
    0.599083921f, 0.248925516f, 0.10244649f, 0.21507582f, 0.885068502f, -0.100144322f, -0.03206585f, -0.027658391f, 1.148781991f,  // 8 SG3C
    0.938279849f, -0.004451446f, 0.016627524f, 0.337368891f, 0.729521567f, -0.066890457f, 0.001173951f, -0.003710706f, 1.091594506f,  // 9 AP0
    0.652237542f, 0.128236136f, 0.169982249f, 0.26767218f, 0.674339989f, 0.057987831f, -0.005381816f, 0.00136906f, 1.093070506f,  // 10 AP1
};
SM_CONST float SM_XYZ_TO_RGB[99] = {
    1.516672042f, -0.281478048f, -0.146963633f, -0.464917101f, 1.251423776f, 0.174884609f, 0.064849047f, 0.109139344f, 0.761414622f,  // 0 DWG
    3.240969942f, -1.537383178f, -0.49861076f, -0.969243636f, 1.875967502f, 0.041555057f, 0.05563008f, -0.203976959f, 1.056971514f,  // 1 709
    1.716651188f, -0.355670784f, -0.253366281f, -0.666684352f, 1.616481237f, 0.015768546f, 0.017639857f, -0.042770613f, 0.942103121f,  // 2 2020
    2.493496912f, -0.931383618f, -0.402710784f, -0.82948897f, 1.76266406f, 0.023624686f, 0.03584583f, -0.076172389f, 0.956884524f,  // 3 P3D65
    2.428254487f, -0.882984537f, -0.390212854f, -0.829879676f, 1.761010282f, 0.025484208f, 0.035749687f, -0.077255587f, 0.95796305f,  // 4 P3D60
    2.690225912f, -1.094001937f, -0.425082348f, -0.820082184f, 1.750480908f, 0.026601954f, 0.036245755f, -0.078580837f, 0.958746994f,  // 5 P3DCI
    1.507399899f, -0.245822137f, -0.171611681f, -0.518151727f, 1.355391241f, 0.125878668f, 0.015511698f, -0.007872771f, 0.911916366f,  // 6 SG
    1.507399899f, -0.245822137f, -0.171611681f, -0.518151727f, 1.355391241f, 0.125878668f, 0.015511698f, -0.007872771f, 0.911916366f,  // 7 SG3
    1.846778969f, -0.525986123f, -0.210545211f, -0.444153263f, 1.259442903f, 0.149399973f, 0.040855421f, 0.015640889f, 0.868207249f,  // 8 SG3C
    1.063495491f, 0.00640891f, -0.015806787f, -0.492074128f, 1.368223407f, 0.091337088f, -0.002816462f, 0.004644171f, 0.916418575f,  // 9 AP0
    1.660585326f, -0.315295561f, -0.241509328f, -0.659926063f, 1.60839147f, 0.017298595f, 0.009002569f, -0.003566876f, 0.913643313f,  // 10 AP1
};

SM_FN SMf3 sm_mul(SM_CPTR m, int o, SMf3 c) {
    return smf3(m[o] * c.x + m[o + 1] * c.y + m[o + 2] * c.z,
                m[o + 3] * c.x + m[o + 4] * c.y + m[o + 5] * c.z,
                m[o + 6] * c.x + m[o + 7] * c.y + m[o + 8] * c.z);
}
SM_FN SMf3 sm_to_xyz(SMf3 c, int s) { return sm_mul(SM_RGB_TO_XYZ, s * 9, c); }
SM_FN SMf3 sm_from_xyz(SMf3 c, int s) { return sm_mul(SM_XYZ_TO_RGB, s * 9, c); }

SM_CONST float SM_BRADFORD[18] = {
    0.8951f, 0.2664f, -0.1614f, -0.7502f, 1.7135f, 0.0367f, 0.0389f, -0.0685f, 1.0296f,
    0.98699291f, -0.14705426f, 0.15996265f, 0.43230527f, 0.51836027f, 0.04929123f,
    -0.00852866f, 0.04004282f, 0.96848669f };

// ---------------------------------------------------------------- data level
// Which scale a clip is decoded on is decided by DaVinci Resolve, from the clip
// attribute "Data Level", before the node graph - and OpenFX has no property that
// reports it (the whole 1.4/1.5 header set, ofxColour.h included, cannot express
// signal range). Resolve's "Auto" guesses from the codec, so on Sony log clips it
// can land on the wrong one:
//
//   Data Level = Full   ->  the node receives  CV / 1023
//   Data Level = Video  ->  the node receives  (CV - 64) / 876
//
// Sony's S-Log curves are published on unscaled code values (S-Log3 black = 95,
// 18% grey = 420, 90% white = 598; S-Log2 and S-Log black = 90), so they need the
// first one. Rec.709 and the broadcast curves are legal-anchored and need the
// second. When the two disagree every value entering the log decode is wrong, most
// visibly in the shadows.
//
// The fix is an affine remap of the *code values*, so it must happen in the
// camera's own encoding, before log -> linear: exposure and white balance keep
// working on linear light, untouched by it.
//
// The node is not always handed the camera encoding. Under Resolve Colour
// Management the input transform has already run and the image arrives in the
// timeline space (DaVinci WG/Intermediate, Rec.709, ACEScct...). So the remap
// round-trips: linear -> camera gamut -> camera curve -> remap -> and back. The
// transfer functions and the matrices here are exact inverses of each other, which
// makes the round-trip lossless and the correction identical in every pipeline -
// DaVinci YRGB, RCM and ACES alike. When the node already sits in the camera
// encoding the round-trip collapses to the remap itself.
SM_FN SMf3 sm_fix_levels(SMf3 lin, DevelopParams p) {
    if (p.levelFix == 0) return lin;
    SMf3 cam = (p.levelSpace == p.nodeSpace) ? lin
             : sm_from_xyz(sm_to_xyz(lin, p.nodeSpace), p.levelSpace);
    SMf3 cv = smf3(sm_encode(cam.x, p.levelGamma), sm_encode(cam.y, p.levelGamma),
                   sm_encode(cam.z, p.levelGamma));
    cv = smf3(cv.x * p.levelGain + p.levelOffset, cv.y * p.levelGain + p.levelOffset,
              cv.z * p.levelGain + p.levelOffset);
    cam = smf3(sm_decode(cv.x, p.levelGamma), sm_decode(cv.y, p.levelGamma),
               sm_decode(cv.z, p.levelGamma));
    return (p.levelSpace == p.nodeSpace) ? cam
         : sm_from_xyz(sm_to_xyz(cam, p.levelSpace), p.nodeSpace);
}

// ---------------------------------------------------------------- false colour
// Three measuring views, one for each of the controls they serve. Each one replaces
// the picture with a banded map, because DaVinci Resolve gives an OpenFX plugin no
// way to draw over the viewer: the image is the only output there is.
//
// They are measured straight after exposure and white balance and BEFORE the tone
// and saturation trims, so that they answer only to the three controls they belong
// to. A saturation trim would scale the chromaticity deviation and make the Kelvin
// readout lie; a contrast trim would move the stops.
//
// Exposure is banded in stops around 18% grey, the way an ARRI-style false colour
// is: green on middle grey, pink one stop over it where skin sits, yellow a stop
// below clip, red clipped, blue and purple at the bottom, and plain greys in
// between so the picture stays readable.
//
// Temperature and tint are banded in the units of their own sliders. Each pixel's
// distance from the working space white is projected through the inverse of the
// slider response measured in buildParams, so the number behind a band is literally
// "how far this slider is from making this pixel neutral". White is neutral, and a
// band's colour is the cast that is really there: warm up what reads blue, take
// green out of what reads green. Pixels too dark to carry a reliable hue, and
// clipped ones whose hue means nothing, are marked instead of guessed.

SM_FN SMf3 sm_fc_exposure(float ev) {
    if (ev >= 5.5f) return smf3(0.96f, 0.16f, 0.10f);                    // clipped
    if (ev >= 4.0f) return smf3(1.00f, 0.88f, 0.12f);                    // a stop from clip
    if (ev >= 0.70f && ev <= 1.30f) return smf3(1.00f, 0.56f, 0.72f);    // skin, one stop over grey
    if (ev >= -0.33f && ev <= 0.33f) return smf3(0.13f, 0.82f, 0.20f);   // 18% grey
    if (ev <= -6.0f) return smf3(0.42f, 0.12f, 0.62f);                   // black clip
    if (ev <= -4.0f) return smf3(0.10f, 0.28f, 0.88f);                   // deep shadow
    float g = sm_clamp((ev + 6.0f) / 11.5f, 0.06f, 0.92f);
    return smf3(g, g, g);
}

SM_FN SMf3 sm_fc_band(float dev, float centre, float mid, float wide, float limit,
                      SMf3 p1, SMf3 p2, SMf3 p3, SMf3 n1, SMf3 n2, SMf3 n3, float mono) {
    float a = dev < 0.0f ? -dev : dev;
    // Inside the tolerance the pixel is left as it is, in monochrome: painting a
    // flat colour on everything hides the one thing the view is for, which is
    // seeing WHICH parts of the picture are already neutral. Outside it the colour
    // arrives as a step, so the edge of the tolerance is a visible boundary and
    // not a gradient you have to judge by eye.
    //
    // Past `limit` it goes back to monochrome, and that is what makes the view
    // readable on a real scene. A red jumper or green foliage sits thousands of
    // Kelvin from neutral - measured: a blue sky 8300 K, a red 14700 K, skin
    // 3200 K - while even a 2500 K white balance error on a neutral surface only
    // reads 1758 K. Beyond the limit it is the colour of the object, not a cast,
    // so it is left out of the judgement instead of being painted over.
    if (a <= centre || a > limit) return smf3(mono, mono, mono);
    if (dev > 0.0f) return a <= mid ? p1 : (a <= wide ? p2 : p3);
    return a <= mid ? n1 : (a <= wide ? n2 : n3);
}

SM_FN SMf3 sm_false_color(SMf3 xyz, DevelopParams p) {
    float y = xyz.y > 1e-9f ? xyz.y : 1e-9f;
    float ev = SM_LOG2(y / 0.18f);
    if (p.fcMode == 1) return sm_fc_exposure(ev);
    float mono = sm_clamp((ev + 6.0f) / 11.5f, 0.06f, 0.92f);   // the picture underneath
    if (ev >= 5.5f) return smf3(0.96f, 0.16f, 0.10f);    // clipped: the hue is meaningless
    if (ev <= -4.0f) return smf3(0.11f, 0.11f, 0.13f);   // too dark to read a cast
    float d = xyz.x + 15.0f * xyz.y + 3.0f * xyz.z;
    if (d < 1e-9f) return smf3(0.11f, 0.11f, 0.13f);
    float du = 4.0f * xyz.x / d - p.fcU;                 // CIE 1960 uv, as the white balance uses
    float dv = 6.0f * xyz.y / d - p.fcV;
    if (p.fcMode == 2)
        return sm_fc_band(-(p.fcKu * du + p.fcKv * dv), 75.0f, 300.0f, 1200.0f, 2500.0f,
                          smf3(0.55f, 0.86f, 1.00f), smf3(0.15f, 0.55f, 1.00f), smf3(0.09f, 0.18f, 0.85f),
                          smf3(1.00f, 0.88f, 0.25f), smf3(1.00f, 0.55f, 0.10f), smf3(0.90f, 0.20f, 0.08f), mono);
    return sm_fc_band(-(p.fcTu * du + p.fcTv * dv), 2.0f, 6.0f, 15.0f, 30.0f,
                      smf3(0.66f, 1.00f, 0.62f), smf3(0.22f, 0.86f, 0.26f), smf3(0.05f, 0.58f, 0.10f),
                      smf3(1.00f, 0.70f, 0.98f), smf3(0.92f, 0.25f, 0.85f), smf3(0.62f, 0.05f, 0.58f), mono);
}

// The palette is a colour meant for a screen. Take it back to linear Rec.709, into
// the gamut the node is writing to, and re-encode it there, so the bands come out
// the same whatever the timeline works in.
SM_FN SMf3 sm_fc_emit(SMf3 c, DevelopParams p) {
    int space = p.convert != 0 ? p.outSpace : p.nodeSpace;
    int gamma = p.convert != 0 ? p.outGamma : p.nodeGamma;
    SMf3 lin = smf3(sm_decode(c.x, 2), sm_decode(c.y, 2), sm_decode(c.z, 2));
    SMf3 o = sm_from_xyz(sm_to_xyz(lin, 1), space);
    return smf3(sm_encode(o.x, gamma), sm_encode(o.y, gamma), sm_encode(o.z, gamma));
}

// ---------------------------------------------------------------- tone
// A highlight shoulder and a shadow toe, both POINTWISE: the output of a pixel
// depends on that pixel alone, so neither can make a halo. That matters, because
// the halo people blame on a highlight control is usually not made by it - a
// pointwise monotone curve cannot invert a gradient or create a local extremum
// (out = f(in) with f' >= 0 gives grad_out = f'(in) * grad_in, same sign). What it
// does is *unmask* what clipping was hiding: lens veiling glare around a blown
// window, codec ringing at a hard edge, a debayer sharpener's overshoot. Compress
// the top of the scale and those become visible.
//
// What this stage can still get wrong, and guards against:
//  - a knee with a slope or curvature jump prints a contour. In a smooth gradient
//    the pixels at the knee value form a level set, and around a bright source
//    those level sets are concentric - a ring that reads exactly like a halo. So
//    the shoulder is C-infinity: one expression, no junction, nothing to print.
//  - max(RGB) as the norm switches which channel defines it across an edge where
//    one channel clips. A pointwise function of a spatially discontinuous quantity
//    makes fringes. The power norm below is smooth and has no such switch.
//  - scaling all three channels leaves *saturation* untouched, so a compressed
//    highlight keeps all its colour and renders as an even, fully chromatic patch
//    with no internal shading - a bright forehead going flat pink. Purity has to
//    be reduced explicitly; a ratio-preserving curve never burns out on its own.

SM_CONST float SM_TONE_KNEE = 3.0f;        // shoulder sharpness: 18% grey moves 0.003 stop
SM_CONST float SM_TONE_PURITY = 0.5f;      // bright skin at +3 stops keeps saturation ~0.30
SM_CONST float SM_TONE_PURITY_GROW = 1.0f; // and the very top still goes to white
SM_CONST float SM_TONE_SHAD_MID = -4.0f;   // shadow bell centre, stops from grey
SM_CONST float SM_TONE_SHAD_W = 1.8f;      // width: at 2.1 the curve would solarise
SM_CONST float SM_TONE_SHAD_AMP = 1.5f;    // stops of lift at full
SM_CONST float SM_TONE_HIGH_MID = 3.5f;   // far enough from grey that it leaves it alone
SM_CONST float SM_TONE_HIGH_W = 1.6f;
SM_CONST float SM_TONE_HIGH_AMP = 1.0f;

// norm(x, x, x) = x exactly, so a neutral pixel is untouched whatever the setting.
SM_FN float sm_tone_norm(SMf3 c) {
    float ax = c.x < 0.0f ? -c.x : c.x;
    float ay = c.y < 0.0f ? -c.y : c.y;
    float az = c.z < 0.0f ? -c.z : c.z;
    float den = c.x * c.x + c.y * c.y + c.z * c.z;
    return den > 1e-12f ? (ax * ax * ax + ay * ay * ay + az * az * az) / den : 0.0f;
}

SM_FN float sm_tone_bell(float ev, float mid, float width) {
    float z = (ev - mid) / width;
    return SM_EXP2(-z * z * 1.4426950408889634f);   // exp(-z*z)
}

SM_FN SMf3 sm_tone(SMf3 rgb, DevelopParams p) {
    float norm = sm_tone_norm(rgb);
    if (norm <= 1e-6f) return rgb;
    float ev = SM_LOG2(norm / 0.18f);

    // Shadows, and Highlights when it brightens: a bell in log2 space, centred well
    // clear of mid grey and dying out at both ends, so neither the midtones nor the
    // foot of the black move. It is a gain, so f(0) = 0 at every setting: absolute
    // black stays absolute black, and the noise floor is left where it was.
    float lift = p.shadows * SM_TONE_SHAD_AMP * sm_tone_bell(ev, SM_TONE_SHAD_MID, SM_TONE_SHAD_W)
               + SM_MAX(p.highlights, 0.0f) * SM_TONE_HIGH_AMP
                 * sm_tone_bell(ev, SM_TONE_HIGH_MID, SM_TONE_HIGH_W);
    float t = SM_EXP2(lift);

    // Highlights when it recovers: the shoulder. Folds the top of the scene towards
    // an asymptote it never reaches, so however bright the scene is it never clips.
    float a = SM_MAX(-p.highlights, 0.0f);
    if (a > 0.0f) {
        // L / (1 + (L*a)^n)^(1/n) written as (L^-n + a^n)^(-1/n): the same curve,
        // but the soft-minimum form never raises a large number to the power n.
        // Written the first way, (L*a)^3 overflows float32 past L*a ~ 7e12 and the
        // infinite divisor turns the brightest pixel in the frame black. Here a
        // huge L simply underflows to 0 and the result lands exactly on 1/a, the
        // asymptote. The early return above keeps L large enough that L^-n is safe.
        float L = norm * t;
        t = SM_POW(SM_POW(L, -SM_TONE_KNEE) + SM_POW(a, SM_TONE_KNEE),
                   -1.0f / SM_TONE_KNEE) / norm;
    }
    SMf3 out = smf3(rgb.x * t, rgb.y * t, rgb.z * t);

    // Purity falls with the compression, which is what takes a recovered sky off
    // neon and a recovered forehead off flat pink. Color Recovery moves the
    // exponent: right hands colour back, left goes towards film. It can only ever
    // restore what the curve took - never add chroma the pixel did not have.
    // The exponent grows where the curve compressed hardest, the way OpenDRT's
    // purity limit does. A single power law can hit the skin target or the top of
    // the scale but not both: without this a sky six stops over stays visibly
    // coloured while its luminance is already at white.
    float k = SM_TONE_PURITY * (1.0f + SM_TONE_PURITY_GROW * SM_MAX(1.0f - t, 0.0f))
            * SM_EXP2(-p.chromaRecover);
    float purity = t < 1.0f ? SM_POW(t, k) : 1.0f;
    purity -= SM_MAX(p.chromaRecover, 0.0f) * SM_MAX(lift, 0.0f) * 0.4f;
    if (purity < 1.0f) {
        purity = sm_clamp(purity, 0.0f, 1.0f);
        float yl = sm_to_xyz(out, p.nodeSpace).y;
        out = smf3(yl + (out.x - yl) * purity, yl + (out.y - yl) * purity,
                   yl + (out.z - yl) * purity);
    }
    return out;
}

// ---------------------------------------------------------------- develop one pixel

SM_FN SMf3 sm_develop(SMf3 in, DevelopParams p) {
    if (p.bypass != 0 && p.levelFix == 0) return in;
    SMf3 lin = smf3(sm_decode(in.x, p.nodeGamma), sm_decode(in.y, p.nodeGamma),
                    sm_decode(in.z, p.nodeGamma));
    lin = sm_fix_levels(lin, p);
    if (p.bypass != 0)   // data level only: the develop is off for this clip
        return smf3(sm_encode(lin.x, p.nodeGamma), sm_encode(lin.y, p.nodeGamma),
                    sm_encode(lin.z, p.nodeGamma));
    lin = smf3(lin.x * p.expo, lin.y * p.expo, lin.z * p.expo);
    SMf3 xyz = sm_to_xyz(lin, p.nodeSpace);

    // white balance: von Kries in Bradford LMS, as-shot white -> chosen white
    SMf3 lms = sm_mul(SM_BRADFORD, 0, xyz);
    lms = smf3(lms.x * p.ratioL, lms.y * p.ratioM, lms.z * p.ratioS);
    xyz = sm_mul(SM_BRADFORD, 9, lms);
    xyz = smf3(xyz.x * p.norm, xyz.y * p.norm, xyz.z * p.norm);

    // a measuring view answers to exposure and white balance only: it is taken here,
    // before the trims below could scale a deviation or move a stop
    if (p.fcMode != 0) return sm_fc_emit(sm_false_color(xyz, p), p);

    // contrast: a power law on log2 luminance around 18% grey
    float ev = SM_LOG2(SM_MAX(xyz.y, 1e-6f) / 0.18f);
    float kk = SM_EXP2(ev * p.contrast);
    xyz = smf3(xyz.x * kk, xyz.y * kk, xyz.z * kk);

    // shoulder, toe and chroma: last luminance move, so nothing can push past it
    SMf3 rgb = sm_tone(sm_from_xyz(xyz, p.nodeSpace), p);

    // saturation and color boost (vibrance) around luminance, in the node gamut
    float mx = SM_MAX(rgb.x, SM_MAX(rgb.y, rgb.z));
    float mn = SM_MIN(rgb.x, SM_MIN(rgb.y, rgb.z));
    float satNow = mx > 1e-6f ? sm_clamp((mx - mn) / mx, 0.0f, 1.0f) : 0.0f;
    float sf = (1.0f + p.saturation) * (1.0f + p.boost * (1.0f - satNow));
    float yl = sm_to_xyz(rgb, p.nodeSpace).y;
    rgb = smf3(yl + (rgb.x - yl) * sf, yl + (rgb.y - yl) * sf, yl + (rgb.z - yl) * sf);

    // Color Space / Gamma: like a Color Space Transform from the node space
    if (p.convert == 0)
        return smf3(sm_encode(rgb.x, p.nodeGamma), sm_encode(rgb.y, p.nodeGamma), sm_encode(rgb.z, p.nodeGamma));
    SMf3 o = sm_from_xyz(sm_to_xyz(rgb, p.nodeSpace), p.outSpace);
    return smf3(sm_encode(o.x, p.outGamma), sm_encode(o.y, p.outGamma), sm_encode(o.z, p.outGamma));
}

#ifndef __METAL_VERSION__
// ---------------------------------------------------------------- CPU only: white points

// Planckian locus (Kim et al. 2002), CIE 1931 xy
static inline void sm_planck_xy(double t, double* x, double* y) {
    t = t < 1667.0 ? 1667.0 : (t > 25000.0 ? 25000.0 : t);
    double it = 1000.0 / t, it2 = it * it, it3 = it2 * it;
    double xx = t <= 4000.0 ? -0.2661239 * it3 - 0.2343589 * it2 + 0.8776956 * it + 0.179910
                            : -3.0258469 * it3 + 2.1070379 * it2 + 0.2226347 * it + 0.240390;
    double x2 = xx * xx, x3 = x2 * xx;
    *y = t <= 2222.0 ? -1.1063814 * x3 - 1.34811020 * x2 + 2.18555832 * xx - 0.20219683
       : (t <= 4000.0 ? -0.9549476 * x3 - 1.37418593 * x2 + 2.09137015 * xx - 0.16748867
                      : 3.0817580 * x3 - 5.87338670 * x2 + 3.75112997 * xx - 0.37001483);
    *x = xx;
}
// White of an illuminant at temperature k with tint (positive = greener illuminant,
// so raising Tint makes the image more magenta), as XYZ with Y = 1.
static inline void sm_white_xyz(double k, double tint, double out[3]) {
    double x0, y0, x1, y1;
    sm_planck_xy(k, &x0, &y0);
    sm_planck_xy(k * 1.01, &x1, &y1);
    double d0 = -2.0 * x0 + 12.0 * y0 + 3.0, d1 = -2.0 * x1 + 12.0 * y1 + 3.0;
    double u0 = 4.0 * x0 / d0, v0 = 6.0 * y0 / d0, u1 = 4.0 * x1 / d1, v1 = 6.0 * y1 / d1;
    double du = u1 - u0, dv = v1 - v0, len = sqrt(du * du + dv * dv);
    double nu = -dv / len, nv = du / len;
    if (nv < 0.0) { nu = -nu; nv = -nv; }
    double u = u0 + nu * tint / 3000.0, v = v0 + nv * tint / 3000.0;
    double d = 2.0 * u - 8.0 * v + 4.0, x = 3.0 * u / d, y = 2.0 * v / d;
    out[0] = x / y; out[1] = 1.0; out[2] = (1.0 - x - y) / y;
}
static inline void sm_bradford(const double in[3], double out[3], int inverse) {
    const float* m = SM_BRADFORD + (inverse ? 9 : 0);
    for (int i = 0; i < 3; ++i)
        out[i] = m[i * 3] * in[0] + m[i * 3 + 1] * in[1] + m[i * 3 + 2] * in[2];
}
// Fill the white-balance fields of DevelopParams from as-shot and chosen Kelvin/tint.
static inline void sm_set_white_balance(DevelopParams* p, double shotK, double shotTint, double k, double tint) {
    double ws[3], wt[3], ls[3], lt[3];
    sm_white_xyz(shotK, shotTint, ws);
    sm_white_xyz(k, tint, wt);
    sm_bradford(ws, ls, 0);
    sm_bradford(wt, lt, 0);
    double r[3] = { ls[0] / lt[0], ls[1] / lt[1], ls[2] / lt[2] };
    const double d65[3] = { 0.95046, 1.0, 1.08906 };
    double l65[3], lr[3], nw[3];
    sm_bradford(d65, l65, 0);
    for (int i = 0; i < 3; ++i) lr[i] = l65[i] * r[i];
    sm_bradford(lr, nw, 1);
    p->ratioL = (float)r[0];
    p->ratioM = (float)r[1];
    p->ratioS = (float)r[2];
    p->norm = nw[1] > 0.0 ? (float)(1.0 / nw[1]) : 1.0f;
}
#endif

#endif
