// SPDX-License-Identifier: GPL-3.0-or-later
// S-Log MetaRaw develop math, shared by the CPU path (C++) and the Metal kernel
// (this file is embedded as source text in the kernel). Reference implementation
// for the tests: tests/develop_model.py.
// GENERATED by tools/build_math.py from DevelopMath.h.in - do not edit DevelopMath.h.
#ifndef SONYMETA_DEVELOP_MATH_H
#define SONYMETA_DEVELOP_MATH_H

#ifdef __METAL_VERSION__
#define SM_FN inline
#define SM_CONST constant
#define SM_CPTR constant float*
#define SM_POW pow
#define SM_LOG2 log2
#define SM_LOG10 log10
#define SM_EXP2 exp2
#define SM_MAX fmax
#define SM_MIN fmin
#else
#include <math.h>
#define SM_FN static inline
#define SM_CONST static const
#define SM_CPTR const float*
#define SM_POW powf
#define SM_LOG2 log2f
#define SM_LOG10 log10f
#define SM_EXP2 exp2f
#define SM_MAX fmaxf
#define SM_MIN fminf
#endif

struct SMf3 { float x; float y; float z; };

SM_FN SMf3 smf3(float x, float y, float z) { SMf3 r; r.x = x; r.y = y; r.z = z; return r; }
SM_FN float sm_clamp(float v, float a, float b) { return SM_MIN(SM_MAX(v, a), b); }

// All-scalar layout so it is identical in C++ and Metal.
struct DevelopParams {
    int bypass;        // 1 = pass the image through untouched
    int convert;       // 1 = Color Space / Gamma differ from the node space
    int nodeSpace;     // gamut code of the image entering the node
    int nodeGamma;     // transfer code of the image entering the node
    int outSpace;
    int outGamma;
    float expo;        // chosen EI / EI at capture
    float ratioL;      // Bradford LMS white ratios (as-shot white / chosen white)
    float ratioM;
    float ratioS;
    float norm;        // keeps the luminance of D65 unchanged by the WB move
    float shadows;
    float highlights;
    float contrast;
    float saturation;
    float boost;
};

// ---------------------------------------------------------------- transfer functions
// codes: 0 DaVinci Intermediate, 1 Linear, 2 Gamma 2.2, 3 Gamma 2.4, 4 Gamma 2.6,
//        5 Rec.709 (BT.709 OETF), 6 sRGB, 7 SLog, 8 SLog2, 9 SLog3, 10 ACEScct

SM_FN float sm_spow(float x, float p) { return x < 0.0f ? -SM_POW(-x, p) : SM_POW(x, p); }

SM_FN float sm_slog_enc(float r) {  // Sony S-Log core, r = reflection / 0.9 (Sony papers)
    float y = r >= 0.0f ? 0.432699f * SM_LOG10(r + 0.037584f) + 0.616596f + 0.03f
                        : r * 5.0f + 0.030001222851889303f;
    return (y * 876.0f + 64.0f) / 1023.0f;
}
SM_FN float sm_slog_dec(float x) {
    float y = (x * 1023.0f - 64.0f) / 876.0f;
    return y >= 0.030001222851889303f ? SM_POW(10.0f, (y - 0.616596f - 0.03f) / 0.432699f) - 0.037584f
                                      : (y - 0.030001222851889303f) / 5.0f;
}

SM_FN float sm_encode(float y, int g) {
    if (g == 0) return y <= 0.00262409f ? y * 10.44426855f : (SM_LOG2(y + 0.0075f) + 7.0f) * 0.07329248f;
    if (g == 2) return sm_spow(y, 1.0f / 2.2f);
    if (g == 3) return sm_spow(y, 1.0f / 2.4f);
    if (g == 4) return sm_spow(y, 1.0f / 2.6f);
    if (g == 5) return y < 0.018f ? 4.5f * y : 1.099f * SM_POW(y, 0.45f) - 0.099f;
    if (g == 6) return y <= 0.0031308f ? 12.92f * y : 1.055f * SM_POW(y, 1.0f / 2.4f) - 0.055f;
    if (g == 7) return sm_slog_enc(y / 0.9f);
    if (g == 8) return sm_slog_enc(y * 155.0f / 219.0f / 0.9f);
    if (g == 9) return y >= 0.01125f ? (420.0f + SM_LOG10((y + 0.01f) / 0.19f) * 261.5f) / 1023.0f
                                     : (y * (171.2102946929f - 95.0f) / 0.01125f + 95.0f) / 1023.0f;
    if (g == 10) return y <= 0.0078125f ? 10.5402377416545f * y + 0.0729055341958355f : (SM_LOG2(y) + 9.72f) / 17.52f;
    return y;
}
SM_FN float sm_decode(float x, int g) {
    if (g == 0) return x <= 0.02740668f ? x / 10.44426855f : SM_EXP2(x / 0.07329248f - 7.0f) - 0.0075f;
    if (g == 2) return sm_spow(x, 2.2f);
    if (g == 3) return sm_spow(x, 2.4f);
    if (g == 4) return sm_spow(x, 2.6f);
    if (g == 5) return x < 0.081f ? x / 4.5f : SM_POW((x + 0.099f) / 1.099f, 1.0f / 0.45f);
    if (g == 6) return x <= 0.04045f ? x / 12.92f : SM_POW((x + 0.055f) / 1.055f, 2.4f);
    if (g == 7) return sm_slog_dec(x) * 0.9f;
    if (g == 8) return sm_slog_dec(x) * 0.9f * 219.0f / 155.0f;
    if (g == 9) return x >= 171.2102946929f / 1023.0f ? SM_POW(10.0f, (x * 1023.0f - 420.0f) / 261.5f) * 0.19f - 0.01f
                                                      : (x * 1023.0f - 95.0f) * 0.01125f / (171.2102946929f - 95.0f);
    if (g == 10) return x <= 0.155251141552511f ? (x - 0.0729055341958355f) / 10.5402377416545f : SM_EXP2(x * 17.52f - 9.72f);
    return x;
}

// ---------------------------------------------------------------- matrices (adapted to D65)
// codes: 0 DaVinci WG, 1 Rec.709, 2 Rec.2020, 3 P3 D65, 4 P3 D60, 5 P3 DCI, 6 S-Gamut,
//        7 S-Gamut3, 8 S-Gamut3.Cine, 9 ACES AP0, 10 ACES AP1

SM_CONST float SM_RGB_TO_XYZ[99] = {
    0.700622392f, 0.148774815f, 0.10105872f, 0.274118511f, 0.873631896f, -0.147750407f, -0.098962913f, -0.137895325f, 1.325915989f,  // 0 DWG
    0.412390799f, 0.357584339f, 0.180480788f, 0.212639006f, 0.715168679f, 0.072192315f, 0.019330819f, 0.11919478f, 0.950532152f,  // 1 709
    0.636958048f, 0.144616904f, 0.168880975f, 0.262700212f, 0.677998072f, 0.059301716f, 0.0f, 0.028072693f, 1.060985058f,  // 2 2020
    0.486570949f, 0.265667693f, 0.198217285f, 0.228974564f, 0.691738522f, 0.079286914f, 0.0f, 0.045113382f, 1.043944369f,  // 3 P3D65
    0.497045658f, 0.257803898f, 0.195606372f, 0.234228848f, 0.688681965f, 0.077089187f, 0.000340577f, 0.04591839f, 1.042798784f,  // 4 P3D60
    0.459251655f, 0.295791788f, 0.195412485f, 0.215150512f, 0.709133637f, 0.075715851f, 0.000272006f, 0.046939514f, 1.041846231f,  // 5 P3DCI
    0.706482713f, 0.12880105f, 0.115172164f, 0.270979671f, 0.786606411f, -0.057586082f, -0.009677845f, 0.004600037f, 1.094135559f,  // 6 SG
    0.706482713f, 0.12880105f, 0.115172164f, 0.270979671f, 0.786606411f, -0.057586082f, -0.009677845f, 0.004600037f, 1.094135559f,  // 7 SG3
    0.599083921f, 0.248925516f, 0.10244649f, 0.21507582f, 0.885068502f, -0.100144322f, -0.03206585f, -0.027658391f, 1.148781991f,  // 8 SG3C
    0.938279849f, -0.004451446f, 0.016627524f, 0.337368891f, 0.729521567f, -0.066890457f, 0.001173951f, -0.003710706f, 1.091594506f,  // 9 AP0
    0.652237542f, 0.128236136f, 0.169982249f, 0.26767218f, 0.674339989f, 0.057987831f, -0.005381816f, 0.00136906f, 1.093070506f,  // 10 AP1
};
SM_CONST float SM_XYZ_TO_RGB[99] = {
    1.516672042f, -0.281478048f, -0.146963633f, -0.464917101f, 1.251423776f, 0.174884609f, 0.064849047f, 0.109139344f, 0.761414622f,  // 0 DWG
    3.240969942f, -1.537383178f, -0.49861076f, -0.969243636f, 1.875967502f, 0.041555057f, 0.05563008f, -0.203976959f, 1.056971514f,  // 1 709
    1.716651188f, -0.355670784f, -0.253366281f, -0.666684352f, 1.616481237f, 0.015768546f, 0.017639857f, -0.042770613f, 0.942103121f,  // 2 2020
    2.493496912f, -0.931383618f, -0.402710784f, -0.82948897f, 1.76266406f, 0.023624686f, 0.03584583f, -0.076172389f, 0.956884524f,  // 3 P3D65
    2.428254487f, -0.882984537f, -0.390212854f, -0.829879676f, 1.761010282f, 0.025484208f, 0.035749687f, -0.077255587f, 0.95796305f,  // 4 P3D60
    2.690225912f, -1.094001937f, -0.425082348f, -0.820082184f, 1.750480908f, 0.026601954f, 0.036245755f, -0.078580837f, 0.958746994f,  // 5 P3DCI
    1.507399899f, -0.245822137f, -0.171611681f, -0.518151727f, 1.355391241f, 0.125878668f, 0.015511698f, -0.007872771f, 0.911916366f,  // 6 SG
    1.507399899f, -0.245822137f, -0.171611681f, -0.518151727f, 1.355391241f, 0.125878668f, 0.015511698f, -0.007872771f, 0.911916366f,  // 7 SG3
    1.846778969f, -0.525986123f, -0.210545211f, -0.444153263f, 1.259442903f, 0.149399973f, 0.040855421f, 0.015640889f, 0.868207249f,  // 8 SG3C
    1.063495491f, 0.00640891f, -0.015806787f, -0.492074128f, 1.368223407f, 0.091337088f, -0.002816462f, 0.004644171f, 0.916418575f,  // 9 AP0
    1.660585326f, -0.315295561f, -0.241509328f, -0.659926063f, 1.60839147f, 0.017298595f, 0.009002569f, -0.003566876f, 0.913643313f,  // 10 AP1
};

SM_FN SMf3 sm_mul(SM_CPTR m, int o, SMf3 c) {
    return smf3(m[o] * c.x + m[o + 1] * c.y + m[o + 2] * c.z,
                m[o + 3] * c.x + m[o + 4] * c.y + m[o + 5] * c.z,
                m[o + 6] * c.x + m[o + 7] * c.y + m[o + 8] * c.z);
}
SM_FN SMf3 sm_to_xyz(SMf3 c, int s) { return sm_mul(SM_RGB_TO_XYZ, s * 9, c); }
SM_FN SMf3 sm_from_xyz(SMf3 c, int s) { return sm_mul(SM_XYZ_TO_RGB, s * 9, c); }

SM_CONST float SM_BRADFORD[18] = {
    0.8951f, 0.2664f, -0.1614f, -0.7502f, 1.7135f, 0.0367f, 0.0389f, -0.0685f, 1.0296f,
    0.98699291f, -0.14705426f, 0.15996265f, 0.43230527f, 0.51836027f, 0.04929123f,
    -0.00852866f, 0.04004282f, 0.96848669f };

// ---------------------------------------------------------------- develop one pixel

SM_FN SMf3 sm_develop(SMf3 in, DevelopParams p) {
    if (p.bypass != 0) return in;
    SMf3 lin = smf3(sm_decode(in.x, p.nodeGamma) * p.expo, sm_decode(in.y, p.nodeGamma) * p.expo,
                    sm_decode(in.z, p.nodeGamma) * p.expo);
    SMf3 xyz = sm_to_xyz(lin, p.nodeSpace);

    // white balance: von Kries in Bradford LMS, as-shot white -> chosen white
    SMf3 lms = sm_mul(SM_BRADFORD, 0, xyz);
    lms = smf3(lms.x * p.ratioL, lms.y * p.ratioM, lms.z * p.ratioS);
    xyz = sm_mul(SM_BRADFORD, 9, lms);
    xyz = smf3(xyz.x * p.norm, xyz.y * p.norm, xyz.z * p.norm);

    // tone: shadows / highlights / contrast on log2 luminance around 18% grey
    float ev = SM_LOG2(SM_MAX(xyz.y, 1e-6f) / 0.18f);
    float wh = sm_clamp(ev / 5.0f, 0.0f, 1.0f);
    float wsh = sm_clamp(-ev / 5.0f, 0.0f, 1.0f);
    float kk = SM_EXP2(ev * p.contrast + p.highlights * 2.0f * wh * wh + p.shadows * 2.0f * wsh * wsh);
    xyz = smf3(xyz.x * kk, xyz.y * kk, xyz.z * kk);

    // saturation and color boost (vibrance) around luminance, in the node gamut
    SMf3 rgb = sm_from_xyz(xyz, p.nodeSpace);
    float mx = SM_MAX(rgb.x, SM_MAX(rgb.y, rgb.z));
    float mn = SM_MIN(rgb.x, SM_MIN(rgb.y, rgb.z));
    float satNow = mx > 1e-6f ? sm_clamp((mx - mn) / mx, 0.0f, 1.0f) : 0.0f;
    float sf = (1.0f + p.saturation) * (1.0f + p.boost * (1.0f - satNow));
    float yl = xyz.y;
    rgb = smf3(yl + (rgb.x - yl) * sf, yl + (rgb.y - yl) * sf, yl + (rgb.z - yl) * sf);

    // Color Space / Gamma: like a Color Space Transform from the node space
    if (p.convert == 0)
        return smf3(sm_encode(rgb.x, p.nodeGamma), sm_encode(rgb.y, p.nodeGamma), sm_encode(rgb.z, p.nodeGamma));
    SMf3 o = sm_from_xyz(sm_to_xyz(rgb, p.nodeSpace), p.outSpace);
    return smf3(sm_encode(o.x, p.outGamma), sm_encode(o.y, p.outGamma), sm_encode(o.z, p.outGamma));
}

#ifndef __METAL_VERSION__
// ---------------------------------------------------------------- CPU only: white points

// Planckian locus (Kim et al. 2002), CIE 1931 xy
static inline void sm_planck_xy(double t, double* x, double* y) {
    t = t < 1667.0 ? 1667.0 : (t > 25000.0 ? 25000.0 : t);
    double it = 1000.0 / t, it2 = it * it, it3 = it2 * it;
    double xx = t <= 4000.0 ? -0.2661239 * it3 - 0.2343589 * it2 + 0.8776956 * it + 0.179910
                            : -3.0258469 * it3 + 2.1070379 * it2 + 0.2226347 * it + 0.240390;
    double x2 = xx * xx, x3 = x2 * xx;
    *y = t <= 2222.0 ? -1.1063814 * x3 - 1.34811020 * x2 + 2.18555832 * xx - 0.20219683
       : (t <= 4000.0 ? -0.9549476 * x3 - 1.37418593 * x2 + 2.09137015 * xx - 0.16748867
                      : 3.0817580 * x3 - 5.87338670 * x2 + 3.75112997 * xx - 0.37001483);
    *x = xx;
}
// White of an illuminant at temperature k with tint (positive = greener illuminant,
// so raising Tint makes the image more magenta), as XYZ with Y = 1.
static inline void sm_white_xyz(double k, double tint, double out[3]) {
    double x0, y0, x1, y1;
    sm_planck_xy(k, &x0, &y0);
    sm_planck_xy(k * 1.01, &x1, &y1);
    double d0 = -2.0 * x0 + 12.0 * y0 + 3.0, d1 = -2.0 * x1 + 12.0 * y1 + 3.0;
    double u0 = 4.0 * x0 / d0, v0 = 6.0 * y0 / d0, u1 = 4.0 * x1 / d1, v1 = 6.0 * y1 / d1;
    double du = u1 - u0, dv = v1 - v0, len = sqrt(du * du + dv * dv);
    double nu = -dv / len, nv = du / len;
    if (nv < 0.0) { nu = -nu; nv = -nv; }
    double u = u0 + nu * tint / 3000.0, v = v0 + nv * tint / 3000.0;
    double d = 2.0 * u - 8.0 * v + 4.0, x = 3.0 * u / d, y = 2.0 * v / d;
    out[0] = x / y; out[1] = 1.0; out[2] = (1.0 - x - y) / y;
}
static inline void sm_bradford(const double in[3], double out[3], int inverse) {
    const float* m = SM_BRADFORD + (inverse ? 9 : 0);
    for (int i = 0; i < 3; ++i)
        out[i] = m[i * 3] * in[0] + m[i * 3 + 1] * in[1] + m[i * 3 + 2] * in[2];
}
// Fill the white-balance fields of DevelopParams from as-shot and chosen Kelvin/tint.
static inline void sm_set_white_balance(DevelopParams* p, double shotK, double shotTint, double k, double tint) {
    double ws[3], wt[3], ls[3], lt[3];
    sm_white_xyz(shotK, shotTint, ws);
    sm_white_xyz(k, tint, wt);
    sm_bradford(ws, ls, 0);
    sm_bradford(wt, lt, 0);
    double r[3] = { ls[0] / lt[0], ls[1] / lt[1], ls[2] / lt[2] };
    const double d65[3] = { 0.95046, 1.0, 1.08906 };
    double l65[3], lr[3], nw[3];
    sm_bradford(d65, l65, 0);
    for (int i = 0; i < 3; ++i) lr[i] = l65[i] * r[i];
    sm_bradford(lr, nw, 1);
    p->ratioL = (float)r[0];
    p->ratioM = (float)r[1];
    p->ratioS = (float)r[2];
    p->norm = nw[1] > 0.0 ? (float)(1.0 / nw[1]) : 1.0f;
}
#endif

#endif
