// SPDX-License-Identifier: GPL-3.0-or-later
// S-Log MetaRaw develop math, shared by the CPU path (C++) and the Metal kernel
// (this file is embedded as source text in the kernel). Reference implementation
// for the tests: tests/develop_model.py.
// GENERATED by tools/build_math.py from DevelopMath.h.in - do not edit DevelopMath.h.
#ifndef SONYMETA_DEVELOP_MATH_H
#define SONYMETA_DEVELOP_MATH_H

#ifdef __METAL_VERSION__
#define SM_FN inline
#define SM_CONST constant
#define SM_CPTR constant float*
#define SM_POW pow
#define SM_LOG2 log2
#define SM_LOG10 log10
#define SM_EXP2 exp2
#define SM_MAX fmax
#define SM_MIN fmin
#else
#include <math.h>
#define SM_FN static inline
#define SM_CONST static const
#define SM_CPTR const float*
#define SM_POW powf
#define SM_LOG2 log2f
#define SM_LOG10 log10f
#define SM_EXP2 exp2f
#define SM_MAX fmaxf
#define SM_MIN fminf
#endif

// The Tint control, and the as-shot tint that seeds it, are in units of Duv * 3000
// along the normal to the Planckian locus (see sm_white_xyz). Real illuminants live
// inside about Duv +-0.01, i.e. +-30 of these units, so +-100 is already three times
// the whole practical range. Past about 470 the white point leaves the spectral
// locus, Z goes negative and the von Kries ratios come out NEGATIVE - which is not a
// colour cast but a broken image, and one no setting of the slider can undo. Sony's
// acquisition metadata can carry a number well past that (an FX6 clip reading 15.17
// in Resolve's own Camera Raw panel stores 1517), so the limit is enforced here,
// once, for every caller.
#define SM_TINT_LIMIT 100.0

struct SMf3 { float x; float y; float z; };

SM_FN SMf3 smf3(float x, float y, float z) { SMf3 r; r.x = x; r.y = y; r.z = z; return r; }
SM_FN float sm_clamp(float v, float a, float b) { return SM_MIN(SM_MAX(v, a), b); }

// All-scalar layout so it is identical in C++ and Metal.
struct DevelopParams {
    int bypass;        // 1 = pass the image through untouched
    int convert;       // 1 = Color Space / Gamma differ from the node space
    int nodeSpace;     // gamut code of the image entering the node
    int nodeGamma;     // transfer code of the image entering the node
    int outSpace;
    int outGamma;
    float expo;        // chosen EI / EI at capture
    float ratioL;      // Bradford LMS white ratios (as-shot white / chosen white)
    float ratioM;
    float ratioS;
    float norm;        // keeps the luminance of D65 unchanged by the WB move
    float shadows;
    float highlights;
    float eTop;        // top of the linear tank, stops over 18% grey (sm_tone)
    float contrast;
    float saturation;
    float boost;
    int levelFix;      // 1 = rescale the code values before the log decode
    int levelSpace;    // gamut of the domain the rescale happens in (the camera's)
    int levelGamma;    // transfer of that domain (the camera's log curve)
    float levelGain;   // code value -> code value, affine
    float levelOffset;
    int fcMode;        // false colour: 0 off, 1 exposure, 2 temperature, 3 tint
    float fcU;         // CIE 1960 uv of the working space white (D65)
    float fcV;
    float fcKu;        // uv deviation -> Kelvin of slider travel: row 0 of the
    float fcKv;        // inverted slider response measured in buildParams
    float fcTu;        // uv deviation -> tint units: row 1 of the same inverse
    float fcTv;
    float chromaRecover;  // -1..1: colour back into recovered highlights, chroma
                          // noise out of lifted shadows. 0 = the film-natural default
};

// ---------------------------------------------------------------- transfer functions
// codes: 0 DaVinci Intermediate, 1 Linear, 2 Gamma 2.2, 3 Gamma 2.4, 4 Gamma 2.6,
//        5 Rec.709 (BT.709 OETF), 6 sRGB, 7 SLog, 8 SLog2, 9 SLog3, 10 ACEScct

SM_FN float sm_spow(float x, float p) { return x < 0.0f ? -SM_POW(-x, p) : SM_POW(x, p); }

SM_FN float sm_slog_enc(float r) {  // Sony S-Log core, r = reflection / 0.9 (Sony papers)
    float y = r >= 0.0f ? 0.432699f * SM_LOG10(r + 0.037584f) + 0.616596f + 0.03f
                        : r * 5.0f + 0.030001222851889303f;
    return (y * 876.0f + 64.0f) / 1023.0f;
}
SM_FN float sm_slog_dec(float x) {
    float y = (x * 1023.0f - 64.0f) / 876.0f;
    return y >= 0.030001222851889303f ? SM_POW(10.0f, (y - 0.616596f - 0.03f) / 0.432699f) - 0.037584f
                                      : (y - 0.030001222851889303f) / 5.0f;
}

SM_FN float sm_encode(float y, int g) {
    if (g == 0) return y <= 0.00262409f ? y * 10.44426855f : (SM_LOG2(y + 0.0075f) + 7.0f) * 0.07329248f;
    if (g == 2) return sm_spow(y, 1.0f / 2.2f);
    if (g == 3) return sm_spow(y, 1.0f / 2.4f);
    if (g == 4) return sm_spow(y, 1.0f / 2.6f);
    if (g == 5) return y < 0.018f ? 4.5f * y : 1.099f * SM_POW(y, 0.45f) - 0.099f;
    if (g == 6) return y <= 0.0031308f ? 12.92f * y : 1.055f * SM_POW(y, 1.0f / 2.4f) - 0.055f;
    if (g == 7) return sm_slog_enc(y / 0.9f);
    if (g == 8) return sm_slog_enc(y * 155.0f / 219.0f / 0.9f);
    if (g == 9) return y >= 0.01125f ? (420.0f + SM_LOG10((y + 0.01f) / 0.19f) * 261.5f) / 1023.0f
                                     : (y * (171.2102946929f - 95.0f) / 0.01125f + 95.0f) / 1023.0f;
    if (g == 10) return y <= 0.0078125f ? 10.5402377416545f * y + 0.0729055341958355f : (SM_LOG2(y) + 9.72f) / 17.52f;
    return y;
}
SM_FN float sm_decode(float x, int g) {
    if (g == 0) return x <= 0.02740668f ? x / 10.44426855f : SM_EXP2(x / 0.07329248f - 7.0f) - 0.0075f;
    if (g == 2) return sm_spow(x, 2.2f);
    if (g == 3) return sm_spow(x, 2.4f);
    if (g == 4) return sm_spow(x, 2.6f);
    if (g == 5) return x < 0.081f ? x / 4.5f : SM_POW((x + 0.099f) / 1.099f, 1.0f / 0.45f);
    if (g == 6) return x <= 0.04045f ? x / 12.92f : SM_POW((x + 0.055f) / 1.055f, 2.4f);
    if (g == 7) return sm_slog_dec(x) * 0.9f;
    if (g == 8) return sm_slog_dec(x) * 0.9f * 219.0f / 155.0f;
    if (g == 9) return x >= 171.2102946929f / 1023.0f ? SM_POW(10.0f, (x * 1023.0f - 420.0f) / 261.5f) * 0.19f - 0.01f
                                                      : (x * 1023.0f - 95.0f) * 0.01125f / (171.2102946929f - 95.0f);
    if (g == 10) return x <= 0.155251141552511f ? (x - 0.0729055341958355f) / 10.5402377416545f : SM_EXP2(x * 17.52f - 9.72f);
    return x;
}

// ---------------------------------------------------------------- matrices (adapted to D65)
// codes: 0 DaVinci WG, 1 Rec.709, 2 Rec.2020, 3 P3 D65, 4 P3 D60, 5 P3 DCI, 6 S-Gamut,
//        7 S-Gamut3, 8 S-Gamut3.Cine, 9 ACES AP0, 10 ACES AP1

SM_CONST float SM_RGB_TO_XYZ[99] = {
    0.700622392f, 0.148774815f, 0.10105872f, 0.274118511f, 0.873631896f, -0.147750407f, -0.098962913f, -0.137895325f, 1.325915989f,  // 0 DWG
    0.412390799f, 0.357584339f, 0.180480788f, 0.212639006f, 0.715168679f, 0.072192315f, 0.019330819f, 0.11919478f, 0.950532152f,  // 1 709
    0.636958048f, 0.144616904f, 0.168880975f, 0.262700212f, 0.677998072f, 0.059301716f, 0.0f, 0.028072693f, 1.060985058f,  // 2 2020
    0.486570949f, 0.265667693f, 0.198217285f, 0.228974564f, 0.691738522f, 0.079286914f, 0.0f, 0.045113382f, 1.043944369f,  // 3 P3D65
    0.497045658f, 0.257803898f, 0.195606372f, 0.234228848f, 0.688681965f, 0.077089187f, 0.000340577f, 0.04591839f, 1.042798784f,  // 4 P3D60
    0.459251655f, 0.295791788f, 0.195412485f, 0.215150512f, 0.709133637f, 0.075715851f, 0.000272006f, 0.046939514f, 1.041846231f,  // 5 P3DCI
    0.706482713f, 0.12880105f, 0.115172164f, 0.270979671f, 0.786606411f, -0.057586082f, -0.009677845f, 0.004600037f, 1.094135559f,  // 6 SG
    0.706482713f, 0.12880105f, 0.115172164f, 0.270979671f, 0.786606411f, -0.057586082f, -0.009677845f, 0.004600037f, 1.094135559f,  // 7 SG3
    0.599083921f, 0.248925516f, 0.10244649f, 0.21507582f, 0.885068502f, -0.100144322f, -0.03206585f, -0.027658391f, 1.148781991f,  // 8 SG3C
    0.938279849f, -0.004451446f, 0.016627524f, 0.337368891f, 0.729521567f, -0.066890457f, 0.001173951f, -0.003710706f, 1.091594506f,  // 9 AP0
    0.652237542f, 0.128236136f, 0.169982249f, 0.26767218f, 0.674339989f, 0.057987831f, -0.005381816f, 0.00136906f, 1.093070506f,  // 10 AP1
};
SM_CONST float SM_XYZ_TO_RGB[99] = {
    1.516672042f, -0.281478048f, -0.146963633f, -0.464917101f, 1.251423776f, 0.174884609f, 0.064849047f, 0.109139344f, 0.761414622f,  // 0 DWG
    3.240969942f, -1.537383178f, -0.49861076f, -0.969243636f, 1.875967502f, 0.041555057f, 0.05563008f, -0.203976959f, 1.056971514f,  // 1 709
    1.716651188f, -0.355670784f, -0.253366281f, -0.666684352f, 1.616481237f, 0.015768546f, 0.017639857f, -0.042770613f, 0.942103121f,  // 2 2020
    2.493496912f, -0.931383618f, -0.402710784f, -0.82948897f, 1.76266406f, 0.023624686f, 0.03584583f, -0.076172389f, 0.956884524f,  // 3 P3D65
    2.428254487f, -0.882984537f, -0.390212854f, -0.829879676f, 1.761010282f, 0.025484208f, 0.035749687f, -0.077255587f, 0.95796305f,  // 4 P3D60
    2.690225912f, -1.094001937f, -0.425082348f, -0.820082184f, 1.750480908f, 0.026601954f, 0.036245755f, -0.078580837f, 0.958746994f,  // 5 P3DCI
    1.507399899f, -0.245822137f, -0.171611681f, -0.518151727f, 1.355391241f, 0.125878668f, 0.015511698f, -0.007872771f, 0.911916366f,  // 6 SG
    1.507399899f, -0.245822137f, -0.171611681f, -0.518151727f, 1.355391241f, 0.125878668f, 0.015511698f, -0.007872771f, 0.911916366f,  // 7 SG3
    1.846778969f, -0.525986123f, -0.210545211f, -0.444153263f, 1.259442903f, 0.149399973f, 0.040855421f, 0.015640889f, 0.868207249f,  // 8 SG3C
    1.063495491f, 0.00640891f, -0.015806787f, -0.492074128f, 1.368223407f, 0.091337088f, -0.002816462f, 0.004644171f, 0.916418575f,  // 9 AP0
    1.660585326f, -0.315295561f, -0.241509328f, -0.659926063f, 1.60839147f, 0.017298595f, 0.009002569f, -0.003566876f, 0.913643313f,  // 10 AP1
};

SM_FN SMf3 sm_mul(SM_CPTR m, int o, SMf3 c) {
    return smf3(m[o] * c.x + m[o + 1] * c.y + m[o + 2] * c.z,
                m[o + 3] * c.x + m[o + 4] * c.y + m[o + 5] * c.z,
                m[o + 6] * c.x + m[o + 7] * c.y + m[o + 8] * c.z);
}
SM_FN SMf3 sm_to_xyz(SMf3 c, int s) { return sm_mul(SM_RGB_TO_XYZ, s * 9, c); }
SM_FN SMf3 sm_from_xyz(SMf3 c, int s) { return sm_mul(SM_XYZ_TO_RGB, s * 9, c); }

SM_CONST float SM_BRADFORD[18] = {
    0.8951f, 0.2664f, -0.1614f, -0.7502f, 1.7135f, 0.0367f, 0.0389f, -0.0685f, 1.0296f,
    0.98699291f, -0.14705426f, 0.15996265f, 0.43230527f, 0.51836027f, 0.04929123f,
    -0.00852866f, 0.04004282f, 0.96848669f };

// ---------------------------------------------------------------- data level
// Which scale a clip is decoded on is decided by DaVinci Resolve, from the clip
// attribute "Data Level", before the node graph - and OpenFX has no property that
// reports it (the whole 1.4/1.5 header set, ofxColour.h included, cannot express
// signal range). Resolve's "Auto" guesses from the codec, so on Sony log clips it
// can land on the wrong one:
//
//   Data Level = Full   ->  the node receives  CV / 1023
//   Data Level = Video  ->  the node receives  (CV - 64) / 876
//
// Sony's S-Log curves are published on unscaled code values (S-Log3 black = 95,
// 18% grey = 420, 90% white = 598; S-Log2 and S-Log black = 90), so they need the
// first one. Rec.709 and the broadcast curves are legal-anchored and need the
// second. When the two disagree every value entering the log decode is wrong, most
// visibly in the shadows.
//
// The fix is an affine remap of the *code values*, so it must happen in the
// camera's own encoding, before log -> linear: exposure and white balance keep
// working on linear light, untouched by it.
//
// The node is not always handed the camera encoding. Under Resolve Colour
// Management the input transform has already run and the image arrives in the
// timeline space (DaVinci WG/Intermediate, Rec.709, ACEScct...). So the remap
// round-trips: linear -> camera gamut -> camera curve -> remap -> and back. The
// transfer functions and the matrices here are exact inverses of each other, which
// makes the round-trip lossless and the correction identical in every pipeline -
// DaVinci YRGB, RCM and ACES alike. When the node already sits in the camera
// encoding the round-trip collapses to the remap itself.
SM_FN SMf3 sm_fix_levels(SMf3 lin, DevelopParams p) {
    if (p.levelFix == 0) return lin;
    SMf3 cam = (p.levelSpace == p.nodeSpace) ? lin
             : sm_from_xyz(sm_to_xyz(lin, p.nodeSpace), p.levelSpace);
    SMf3 cv = smf3(sm_encode(cam.x, p.levelGamma), sm_encode(cam.y, p.levelGamma),
                   sm_encode(cam.z, p.levelGamma));
    cv = smf3(cv.x * p.levelGain + p.levelOffset, cv.y * p.levelGain + p.levelOffset,
              cv.z * p.levelGain + p.levelOffset);
    cam = smf3(sm_decode(cv.x, p.levelGamma), sm_decode(cv.y, p.levelGamma),
               sm_decode(cv.z, p.levelGamma));
    return (p.levelSpace == p.nodeSpace) ? cam
         : sm_from_xyz(sm_to_xyz(cam, p.levelSpace), p.nodeSpace);
}

// ---------------------------------------------------------------- false colour
// Three measuring views, one for each of the controls they serve. Each one replaces
// the picture with a banded map, because DaVinci Resolve gives an OpenFX plugin no
// way to draw over the viewer: the image is the only output there is.
//
// They are measured straight after exposure and white balance and BEFORE the tone
// and saturation trims, so that they answer only to the three controls they belong
// to. A saturation trim would scale the chromaticity deviation and make the Kelvin
// readout lie; a contrast trim would move the stops.
//
// Exposure is banded in stops around 18% grey, the way an ARRI-style false colour
// is: green on middle grey, pink one stop over it where skin sits, yellow a stop
// below clip, red clipped, blue and purple at the bottom, and plain greys in
// between so the picture stays readable.
//
// Temperature and tint are banded in the units of their own sliders. Each pixel's
// distance from the working space white is projected through the inverse of the
// slider response measured in buildParams, so the number behind a band is literally
// "how far this slider is from making this pixel neutral". White is neutral, and a
// band's colour is the cast that is really there: warm up what reads blue, take
// green out of what reads green. Pixels too dark to carry a reliable hue, and
// clipped ones whose hue means nothing, are marked instead of guessed.

SM_FN SMf3 sm_fc_exposure(float ev) {
    if (ev >= 5.5f) return smf3(0.96f, 0.16f, 0.10f);                    // clipped
    if (ev >= 4.0f) return smf3(1.00f, 0.88f, 0.12f);                    // a stop from clip
    if (ev >= 0.70f && ev <= 1.30f) return smf3(1.00f, 0.56f, 0.72f);    // skin, one stop over grey
    if (ev >= -0.33f && ev <= 0.33f) return smf3(0.13f, 0.82f, 0.20f);   // 18% grey
    if (ev <= -6.0f) return smf3(0.42f, 0.12f, 0.62f);                   // black clip
    if (ev <= -4.0f) return smf3(0.10f, 0.28f, 0.88f);                   // deep shadow
    float g = sm_clamp((ev + 6.0f) / 11.5f, 0.06f, 0.92f);
    return smf3(g, g, g);
}

SM_FN SMf3 sm_fc_band(float dev, float centre, float mid, float wide, float limit,
                      SMf3 p1, SMf3 p2, SMf3 p3, SMf3 n1, SMf3 n2, SMf3 n3, float mono) {
    float a = dev < 0.0f ? -dev : dev;
    // Inside the tolerance the pixel is left as it is, in monochrome: painting a
    // flat colour on everything hides the one thing the view is for, which is
    // seeing WHICH parts of the picture are already neutral. Outside it the colour
    // arrives as a step, so the edge of the tolerance is a visible boundary and
    // not a gradient you have to judge by eye.
    //
    // Past `limit` it goes back to monochrome, and that is what makes the view
    // readable on a real scene. A red jumper or green foliage sits thousands of
    // Kelvin from neutral - measured: a blue sky 8300 K, a red 14700 K, skin
    // 3200 K - while even a 2500 K white balance error on a neutral surface only
    // reads 1758 K. Beyond the limit it is the colour of the object, not a cast,
    // so it is left out of the judgement instead of being painted over.
    if (a <= centre || a > limit) return smf3(mono, mono, mono);
    if (dev > 0.0f) return a <= mid ? p1 : (a <= wide ? p2 : p3);
    return a <= mid ? n1 : (a <= wide ? n2 : n3);
}

SM_FN SMf3 sm_false_color(SMf3 xyz, DevelopParams p) {
    float y = xyz.y > 1e-9f ? xyz.y : 1e-9f;
    float ev = SM_LOG2(y / 0.18f);
    if (p.fcMode == 1) return sm_fc_exposure(ev);
    float mono = sm_clamp((ev + 6.0f) / 11.5f, 0.06f, 0.92f);   // the picture underneath
    if (ev >= 5.5f) return smf3(0.96f, 0.16f, 0.10f);    // clipped: the hue is meaningless
    if (ev <= -4.0f) return smf3(0.11f, 0.11f, 0.13f);   // too dark to read a cast
    float d = xyz.x + 15.0f * xyz.y + 3.0f * xyz.z;
    if (d < 1e-9f) return smf3(0.11f, 0.11f, 0.13f);
    float du = 4.0f * xyz.x / d - p.fcU;                 // CIE 1960 uv, as the white balance uses
    float dv = 6.0f * xyz.y / d - p.fcV;
    if (p.fcMode == 2)
        return sm_fc_band(-(p.fcKu * du + p.fcKv * dv), 75.0f, 300.0f, 1200.0f, 2500.0f,
                          smf3(0.55f, 0.86f, 1.00f), smf3(0.15f, 0.55f, 1.00f), smf3(0.09f, 0.18f, 0.85f),
                          smf3(1.00f, 0.88f, 0.25f), smf3(1.00f, 0.55f, 0.10f), smf3(0.90f, 0.20f, 0.08f), mono);
    return sm_fc_band(-(p.fcTu * du + p.fcTv * dv), 2.0f, 6.0f, 15.0f, 30.0f,
                      smf3(0.66f, 1.00f, 0.62f), smf3(0.22f, 0.86f, 0.26f), smf3(0.05f, 0.58f, 0.10f),
                      smf3(1.00f, 0.70f, 0.98f), smf3(0.92f, 0.25f, 0.85f), smf3(0.62f, 0.05f, 0.58f), mono);
}

// The palette is a colour meant for a screen. Take it back to linear Rec.709, into
// the gamut the node is writing to, and re-encode it there, so the bands come out
// the same whatever the timeline works in.
SM_FN SMf3 sm_fc_emit(SMf3 c, DevelopParams p) {
    int space = p.convert != 0 ? p.outSpace : p.nodeSpace;
    int gamma = p.convert != 0 ? p.outGamma : p.nodeGamma;
    SMf3 lin = smf3(sm_decode(c.x, 2), sm_decode(c.y, 2), sm_decode(c.z, 2));
    SMf3 o = sm_from_xyz(sm_to_xyz(lin, 1), space);
    return smf3(sm_encode(o.x, gamma), sm_encode(o.y, gamma), sm_encode(o.z, gamma));
}

// ---------------------------------------------------------------- tone
// The scene is a tank of linear light. Middle grey (0.18) is its median, the top of
// the tank is p.eTop stops above it and the bottom SM_TONE_E_BOT stops below.
//
// p.eTop is the top of the curve the CAMERA recorded, not of the timeline and not of
// the picture: S-Log3 holds +7.74 stops over grey (code 1023 = 38.4 linear), S-Log2
// +6.26, S-Log +5.76. It is a property of the format, so it is the same number on
// every frame of every clip shot that way, whatever the timeline is working in.
// Exposure slides the image up and down INSIDE the tank; the tank never moves. An
// auto ceiling taken from the brightest pixel - the trick a 32 bit float audio
// recorder plays with its peak - would make the same Highlights value grade
// differently shot to shot and flicker across a pan, and it would fight the Exposure
// control, which is the thing that is supposed to move the picture.
//
// Highlights is a press that comes down from the top of the tank. It says where the
// top stop lands, in stops, and everything below follows proportionally: the stop
// under the ceiling moves less, the one under that less again, down to middle grey
// which does not move at all. Negative compresses (at -100 the top of the tank lands
// exactly on 1.0 linear, the peak a Rec.709 signal can hold); positive expands, which
// brings a lower scene point up onto the top - the sun that saturates at 60 IRE
// pulled up to 100 with the detail below it stretched rather than clipped.
//
// Both directions are POINTWISE: the output of a pixel depends on that pixel alone,
// so neither can make a halo. A pointwise monotone curve cannot invert a gradient or
// create a local extremum (out = f(in) with f' >= 0 gives grad_out = f'(in) * grad_in,
// same sign). What such a control does is *unmask* what clipping was hiding: lens
// veiling glare around a blown window, codec ringing at a hard edge, a debayer
// sharpener's overshoot.
//
// What this stage guards against, in order of how badly it bit:
//  - LOSING MONOTONICITY. The version before this one scaled the three channels by
//    f(norm)/norm and then pulled them towards luminance by purity = t^k(t). Once f
//    reached its asymptote it was flat while purity kept falling, so the product FELL:
//    a brighter chromatic pixel came out darker, and the top of a sky or a neon read
//    as a negative. Measured, it started at +7.2 stops with Highlights at -10 and at
//    +4.2 stops at -100 - "after a few clicks the image inverts". It is now impossible
//    by construction: the two branches below are each monotone in every channel and
//    the weight between them does not depend on the pixel, so the blend is monotone.
//  - a knee with a slope or curvature jump prints a contour. In a smooth gradient the
//    pixels at the knee value form a level set, and around a bright source those level
//    sets are concentric - a ring that reads exactly like a halo. So the curve is
//    C-infinity: one expression, no junction, nothing to print.
//  - max(RGB) as the norm switches which channel defines it across an edge where one
//    channel clips. A pointwise function of a spatially discontinuous quantity makes
//    fringes. The power norm below is smooth and has no such switch.
//  - blending towards the XYZ Y of a wide gamut. The blue coefficient of Y is negative
//    in DaVinci WG (-0.1478) and in S-Gamut3.Cine (-0.1001), so a saturated blue has
//    Y < 0 and pulling towards it pushed channels BELOW black inside a bright area.
//    Y is gone from the hot path; nothing here can make a channel change sign.

SM_CONST float SM_TONE_GREY = 0.18f;       // scene linear value of 18% grey
// Shoulder sharpness, and the one number that decides how far down the press reaches.
// The drop it applies goes as 2^(n * (e - ceiling)) in stops, so n is literally how
// sharply the effect dies out below the ceiling: the smaller n is, the further down
// the tank the press is felt and the more of the compression is spread over the upper
// scale instead of being piled against the ceiling. Measured at Highlights -100 with
// an S-Log3 container (grey 18%, skin +1 stop, and the separation kept between +3
// stops and the top of the container - which is what "detail in the highlights"
// means numerically):
//
//     n     grey       skin      +3..top
//    2.0   0.023 st   0.088 st   0.284 st
//    2.5   0.008 st   0.043 st   0.195 st   <- this
//    3.0   0.003 st   0.022 st   0.139 st
//
// n = 3 was the old value and it piles everything above +3 stops into a 0.139 stop
// band: the highlights go flat, which is the opposite of keeping detail up there.
// n = 2.5 gives 40% more separation for a midtone move of 0.008 stop, i.e. 0.55% of
// a value - an order of magnitude below anything visible on a flat field. n = 2 buys
// another 0.09 stop of separation for three times the midtone move, which is the
// wrong side of the trade for a control people leave switched on.
SM_CONST float SM_TONE_KNEE = 2.5f;
// How sharply the expansion's ceiling on the lift is approached. A hard min(drop, cap)
// would be only C0 in the gain: the pixels sitting exactly at the corner form a level
// set, and around a bright source those level sets are concentric - a ring, which is
// precisely the artefact this whole stage is built to avoid. Measured before this went
// in: a slope jump of 0.589 at Highlights +100. The soft minimum
// (drop^-m + cap^-m)^(-1/m) is C-infinity, is below both arguments everywhere, and
// approaches the cap without reaching it, so the lift is strictly bounded by 2^cap.
SM_CONST float SM_TONE_CAP_SOFT = 4.0f;
SM_CONST float SM_TONE_E_BOT = -10.0f;     // bottom of the tank, stops under grey
SM_CONST float SM_TONE_E_709 = 2.4739311883324122f;  // log2(1/0.18): the peak Rec.709 holds
SM_CONST float SM_TONE_E_TOP_MIN = 4.0f;   // a clip's container has to be a sane one
SM_CONST float SM_TONE_E_TOP_MAX = 12.0f;
SM_CONST float SM_TONE_E_TOP_DEF = 10.0f;  // used when the clip's curve is not a camera one
SM_CONST float SM_TONE_EXPAND = 2.0f;     // stops of lift at Highlights +100
SM_CONST float SM_TONE_MIX = 0.5f;         // ratio-preserving vs per-channel at Color Recovery 0
SM_CONST float SM_TONE_SHAD_OFF = 6.0f;    // shadow bell centre, stops above the tank floor
SM_CONST float SM_TONE_SHAD_W = 1.8f;      // width: at 2.1 the curve would solarise
SM_CONST float SM_TONE_SHAD_AMP = 1.5f;    // stops of lift at full

// Top of the container a given transfer curve records, in stops over 18% grey: what
// the press comes down from. S-Log3 +7.74 (code 1023 decodes to 38.4 linear), S-Log2
// +6.26, S-Log +5.76, DaVinci Intermediate +9.12. Linear and the display curves have
// no ceiling of their own, so they get the default. One definition, shared by the
// plugin, the Metal kernel and the test harness, so the three cannot drift apart.
SM_FN float sm_tank_top(int gamma) {
    float top = sm_decode(1.0f, gamma);
    if (!(top > 0.0f)) return SM_TONE_E_TOP_DEF;
    float e = SM_LOG2(top / SM_TONE_GREY);
    return (e >= SM_TONE_E_TOP_MIN && e <= SM_TONE_E_TOP_MAX) ? e : SM_TONE_E_TOP_DEF;
}

// norm(x, x, x) = x exactly, so a neutral pixel is untouched whatever the setting.
SM_FN float sm_tone_norm(SMf3 c) {
    float ax = c.x < 0.0f ? -c.x : c.x;
    float ay = c.y < 0.0f ? -c.y : c.y;
    float az = c.z < 0.0f ? -c.z : c.z;
    float den = c.x * c.x + c.y * c.y + c.z * c.z;
    return den > 1e-12f ? (ax * ax * ax + ay * ay * ay + az * az * az) / den : 0.0f;
}

SM_FN float sm_tone_bell(float ev, float mid, float width) {
    float z = (ev - mid) / width;
    return SM_EXP2(-z * z * 1.4426950408889634f);   // exp(-z*z)
}

// Where the top of the tank has to land, in stops over grey, for this setting.
// LINEAR in the slider, which is the whole point: the old law put the ceiling at
// 1/|H| linear, so the first ten clicks moved it from +infinity to +5.8 stops and
// the remaining ninety were worth 3.3 stops between them.
// The travel is the same in both directions, so +H is the exact inverse of -H: at -100
// the top of the tank comes down onto the Rec.709 peak, at +100 the scene point that
// sits on the Rec.709 peak is taken back up to the top of the tank.
SM_FN float sm_tone_ceiling(float eTop, float h) {
    float a = h < 0.0f ? -h : h;
    return eTop - a * (eTop - SM_TONE_E_709);
}

// The asymptote that makes the curve below send the top of the tank exactly to the
// ceiling, in closed form. Solving X_CEIL = X_TOP / (1 + (X_TOP/K)^n)^(1/n) for K:
//     K = X_TOP / ((X_TOP / X_CEIL)^n - 1)^(1/n)
// h = 0 gives K = 0, which the callers read as "identity", so the node is exactly
// neutral at zero without a special case in the curve itself.
SM_FN float sm_tone_asymptote(float eTop, float h) {
    float a = h < 0.0f ? -h : h;
    if (a < 1e-6f || eTop <= SM_TONE_E_709) return 0.0f;
    float xt = SM_TONE_GREY * SM_EXP2(eTop);
    float xc = SM_TONE_GREY * SM_EXP2(sm_tone_ceiling(eTop, h));
    float q = SM_POW(xt / xc, SM_TONE_KNEE) - 1.0f;
    return q <= 0.0f ? 0.0f : xt / SM_POW(q, 1.0f / SM_TONE_KNEE);
}

// One primitive, both ways round. Compression is the soft clip
//     f(x) = x / (1 + (x/K)^n)^(1/n)
// written as (x^-n + K^-n)^(-1/n): the same curve, but the soft-minimum form never
// raises a large number to the power n. Written the first way, (x/K)^n overflows
// float32 past x/K ~ 1.8e19 and the infinite divisor turns the brightest pixel in the
// frame black; here a huge x simply underflows to 0 and the result lands exactly on K.
// f(0) = 0 and f'(0) = 1 exactly, C-infinity for x > 0, and the asymptote K is
// approached but never reached, so no scene value can ever clip.
//
// Expansion is the MIRROR of that move, not its inverse: the same displacement in
// stops, applied upwards, capped at `cap`. The exact inverse f^-1(y) = y/(1-(y/K)^n)^(1/n)
// diverges as y approaches K - and K sits BELOW the top of the tank, so with the
// inverse the whole upper part of the picture would hit a wall and come out as one
// flat value. Measured before the cap went in: at Highlights +50, S-Log3 code 0.80
// came out at 1.145 and everything above it landed on the same number. The mirror form
// is x * 2^softmin(drop, cap): monotone (a positive value times a non-decreasing
// gain), strictly bounded by 2^cap, and it decays going down exactly like the press
// it mirrors.
//
// Odd in x, so a negative channel out of a wide gamut is carried through with its
// sign and its magnitude treated the same as a positive one.
SM_FN float sm_tone_curve(float x, float k, float cap, int expand) {
    if (k <= 0.0f) return x;
    float s = x < 0.0f ? -1.0f : 1.0f;
    float ax = x < 0.0f ? -x : x;
    if (ax < 1e-9f) return x;
    float f = SM_POW(SM_POW(ax, -SM_TONE_KNEE) + SM_POW(k, -SM_TONE_KNEE),
                     -1.0f / SM_TONE_KNEE);
    if (expand == 0) return s * f;
    float drop = SM_LOG2(ax / f);
    if (drop < 1e-9f) return x;
    float lift = SM_POW(SM_POW(drop, -SM_TONE_CAP_SOFT) + SM_POW(cap, -SM_TONE_CAP_SOFT),
                        -1.0f / SM_TONE_CAP_SOFT);
    return s * ax * SM_EXP2(lift);
}

SM_FN SMf3 sm_tone(SMf3 rgb, DevelopParams p) {
    // Shadows: a bell gain in log2, centred a fixed distance above the floor of the
    // tank and dying out at both ends, so neither the midtones nor the noise floor
    // move. It is a gain, so f(0) = 0 at every setting: absolute black stays absolute
    // black. Its slope never drops below 0.285, which is what keeps it monotone.
    if (p.shadows != 0.0f) {
        float n0 = sm_tone_norm(rgb);
        if (n0 > 1e-6f) {
            float bell = sm_tone_bell(SM_LOG2(n0 / SM_TONE_GREY),
                                      SM_TONE_E_BOT + SM_TONE_SHAD_OFF, SM_TONE_SHAD_W);
            float g = SM_EXP2(p.shadows * SM_TONE_SHAD_AMP * bell);
            rgb = smf3(rgb.x * g, rgb.y * g, rgb.z * g);
        }
    }

    const float k = sm_tone_asymptote(p.eTop, p.highlights);
    if (k <= 0.0f) return rgb;                  // Highlights at 0: exact identity
    const int expand = p.highlights > 0.0f ? 1 : 0;
    const float cap = p.highlights * SM_TONE_EXPAND;

    // Ratio-preserving branch: one factor on all three channels, so the pixel keeps
    // every bit of the colour it had. On its own it never burns out towards white - a
    // compressed highlight comes back as an even, fully chromatic patch with no
    // internal shading, the bright forehead going flat pink.
    SMf3 keep = rgb;
    float norm = sm_tone_norm(rgb);
    if (norm > 1e-6f) {
        float t = sm_tone_curve(norm, k, cap, expand) / norm;
        keep = smf3(rgb.x * t, rgb.y * t, rgb.z * t);
    }

    // Per-channel branch: the three channels share one ceiling, so climbing they
    // converge - and converging IS desaturating. That is how film does it: not a
    // desaturation term bolted on, but three layers saturating together. On its own it
    // ties the loss of chroma to the DISTANCE between the channels, which flattens a
    // light, weakly saturated colour like skin while oversaturating mid greens.
    SMf3 film = smf3(sm_tone_curve(rgb.x, k, cap, expand), sm_tone_curve(rgb.y, k, cap, expand),
                     sm_tone_curve(rgb.z, k, cap, expand));

    // Color Recovery picks between the two: right hands the colour back, left goes
    // towards film. Neither branch can ever ADD chroma the pixel did not have. The
    // weight is the same for every pixel, so the blend of two per-channel monotone
    // functions is itself per-channel monotone - this is the guarantee the old
    // purity exponent could not give, and the reason the image cannot invert.
    //
    // Color Recovery used to ALSO pull chroma out of shadows it had lifted, on the
    // grounds that that is where the chroma noise is. It is gone, and not by oversight:
    // along a ray the result reads t*n0*[1 + (r-1)*s(t)], and monotonicity needs
    // 1 + (w'/w)/ln2 + shadows*AMP*bell' > 0 for every weight shape w. The shadow lift
    // alone already spends that budget down to 0.285 at Shadows +100, and any weight
    // that decays to zero has an unbounded -w'/w, so a channel sitting at zero - a
    // saturated primary out of a wide gamut - always inverts somewhere. Measured across
    // shapes: 48497 non-monotone steps with a Gaussian weight, 67912 with a logistic.
    // Chroma noise in the shadows is a denoise problem; it does not belong smuggled
    // into a tone curve that has to promise it cannot invert.
    float w = p.chromaRecover >= 0.0f ? SM_TONE_MIX + p.chromaRecover * (1.0f - SM_TONE_MIX)
                                      : SM_TONE_MIX * (1.0f + p.chromaRecover);
    w = sm_clamp(w, 0.0f, 1.0f);
    return smf3(film.x + (keep.x - film.x) * w, film.y + (keep.y - film.y) * w,
                film.z + (keep.z - film.z) * w);
}

// ---------------------------------------------------------------- gamut
// A colour outside the gamut we are writing to is not a look, it is a signal that
// cannot exist there. Converting a saturated stage LED from S-Gamut3.Cine to
// Rec.709 gives, measured, R -0.125 and G -0.292 - and the waveform folds under
// zero, which is what "the lights and the colours fall apart" looks like on a scope.
//
// The tone press cannot repair that, and not for want of tuning: it multiplies all
// three channels by one POSITIVE factor, so it can walk a negative towards zero and
// never through it. Measured on the same pixel, Highlights at -100 takes that
// -0.125 only as far as -0.072. The same frame written to DaVinci WG comes out
// entirely positive, which is the whole diagnosis in one line: it is the matrix,
// not the curve.
//
// So the ratios are brought back inside. For each channel the distance from the
// achromatic, d = (ac - c) / ac with ac = max(R, G, B), is 0 on the largest
// channel, exactly 1 on a channel sitting at zero, and greater than 1 ONLY when
// the channel is negative. Compressing d towards an asymptote of 1 it never
// reaches is therefore, literally, "never negative" - a property, not a clamp and
// not a taste setting.
//
// Below the threshold nothing moves at all, so a picture that was already inside
// the gamut comes out bit for bit as it went in. Above it, the same soft minimum
// the press uses, so the join is smooth and a colour crossing the boundary does not
// print a contour. And the largest channel never moves: only chroma travels, never
// the level, so everything the tone stage decided about brightness survives this
// untouched.
//
// The threshold is a declared trade. At 0.7 a pure Rec.709 primary - a channel
// sitting exactly at zero, which is legitimately in gamut - comes back up to 6.2%
// of the achromatic. That is the price of the gentlest re-entry, and no control
// gives it back: Color Recovery is the weight between the two branches INSIDE the
// press, which runs before the conversion, so it cannot see this stage at all.
SM_CONST float SM_GAMUT_THRESH = 0.7f;   // distance below which nothing is touched
SM_CONST float SM_GAMUT_KNEE = 3.0f;     // sharpness of the way back in

SM_FN float sm_gamut_one(float v, float ac, float t, float a) {
    float d = (ac - v) / ac;
    // The soft minimum below would raise (d - t) to a negative power, so a distance
    // a hair over the threshold has to take the identity branch it tends to anyway:
    // for a tiny x the compressed distance IS t + x, which gives back v exactly.
    if (d <= t + 1e-6f) return v;
    float x = d - t;
    d = t + SM_POW(SM_POW(x, -SM_GAMUT_KNEE) + SM_POW(a, -SM_GAMUT_KNEE),
                   -1.0f / SM_GAMUT_KNEE);
    return ac * (1.0f - d);
}

// The guarantee, stated the way this actually works: a pixel with a positive
// maximum IN THE SPACE BEING WRITTEN comes out with no negative channel. That is
// the condition, not "there was light in the file": a value at or below the curve's
// own black point already decodes negative on two channels, and a conversion can
// take the third under as well - measured, 13 pixels in 150000 towards DaVinci WG
// and none towards Rec.709. Those have no achromatic to measure against and pass
// through as they are, at about -0.008 in linear, which is ABOVE the -0.014 that
// S-Log3 code zero decodes to: it re-encodes to a legal near-black code. Clamping
// them would hide a decode or data level problem instead of showing one.
SM_FN SMf3 sm_gamut_compress(SMf3 c) {
    float ac = SM_MAX(c.x, SM_MAX(c.y, c.z));
    if (!(ac > 1e-9f)) return c;         // nothing positive to measure against
    const float t = SM_GAMUT_THRESH, a = 1.0f - t;
    return smf3(sm_gamut_one(c.x, ac, t, a), sm_gamut_one(c.y, ac, t, a),
                sm_gamut_one(c.z, ac, t, a));
}

// ---------------------------------------------------------------- develop one pixel

SM_FN SMf3 sm_develop(SMf3 in, DevelopParams p) {
    if (p.bypass != 0 && p.levelFix == 0) return in;
    SMf3 lin = smf3(sm_decode(in.x, p.nodeGamma), sm_decode(in.y, p.nodeGamma),
                    sm_decode(in.z, p.nodeGamma));
    lin = sm_fix_levels(lin, p);
    if (p.bypass != 0)   // data level only: the develop is off for this clip
        return smf3(sm_encode(lin.x, p.nodeGamma), sm_encode(lin.y, p.nodeGamma),
                    sm_encode(lin.z, p.nodeGamma));
    lin = smf3(lin.x * p.expo, lin.y * p.expo, lin.z * p.expo);
    SMf3 xyz = sm_to_xyz(lin, p.nodeSpace);

    // white balance: von Kries in Bradford LMS, as-shot white -> chosen white
    SMf3 lms = sm_mul(SM_BRADFORD, 0, xyz);
    lms = smf3(lms.x * p.ratioL, lms.y * p.ratioM, lms.z * p.ratioS);
    xyz = sm_mul(SM_BRADFORD, 9, lms);
    xyz = smf3(xyz.x * p.norm, xyz.y * p.norm, xyz.z * p.norm);

    // a measuring view answers to exposure and white balance only: it is taken here,
    // before the trims below could scale a deviation or move a stop
    if (p.fcMode != 0) return sm_fc_emit(sm_false_color(xyz, p), p);

    SMf3 rgb = sm_from_xyz(xyz, p.nodeSpace);

    // contrast: a power law on log2 of the SAME power norm the tone stage uses, not on
    // the XYZ luminance. Y has a negative blue coefficient in a wide gamut, so a
    // saturated blue can have Y <= 0; the old max(Y, 1e-6) then read it as -17.4 stops
    // and a negative contrast turned that into a gain of ~1e5 on a single pixel. The
    // norm is non-negative by construction and equals the value itself on a neutral,
    // so grey still pivots exactly where it did. Scaling in RGB or in XYZ is the same
    // multiply, so nothing else about this stage changes.
    if (p.contrast != 0.0f) {
        float cn = sm_tone_norm(rgb);
        if (cn > 1e-6f) {
            float kk = SM_EXP2(SM_LOG2(cn / SM_TONE_GREY) * p.contrast);
            rgb = smf3(rgb.x * kk, rgb.y * kk, rgb.z * kk);
        }
    }

    // Color Space / Gamma: like a Color Space Transform from the node space. It
    // happens HERE, before the press, so that the press and the saturation work in
    // the space the image is actually being written to.
    //
    // The press says where the top of the tank lands, and "the peak a Rec.709 signal
    // holds" is a statement about Rec.709 - it means nothing until we are in it. Run
    // before the conversion, the press judged a saturated colour by its norm in the
    // NODE's gamut, where it was unremarkable, and the matrix could then put it above
    // the destination's white anyway: measured on a stage LED at Highlights -100,
    // 1.088 instead of the 1.0 the control promises. From here it lands at 0.935.
    //
    // Nothing else moves. Every neutral comes out bit for bit as before at every
    // setting of every control, because a grey is a grey in any of these spaces and
    // the norm of a neutral is the neutral itself. Only chromatic pixels see a
    // difference, and only because they are finally being judged where it counts.
    // With Color Space and Gamma on Timeline - the default - there is no conversion
    // at all and this is exactly the code that ran before.
    const int outSpace = p.convert == 0 ? p.nodeSpace : p.outSpace;
    const int outGamma = p.convert == 0 ? p.nodeGamma : p.outGamma;
    SMf3 o = p.convert == 0 ? rgb : sm_from_xyz(sm_to_xyz(rgb, p.nodeSpace), outSpace);

    // press, toe and chroma: last luminance move, so nothing can push past it
    o = sm_tone(o, p);

    // saturation and color boost (vibrance) around luminance, in the output gamut
    float mx = SM_MAX(o.x, SM_MAX(o.y, o.z));
    float mn = SM_MIN(o.x, SM_MIN(o.y, o.z));
    float satNow = mx > 1e-6f ? sm_clamp((mx - mn) / mx, 0.0f, 1.0f) : 0.0f;
    float sf = (1.0f + p.saturation) * (1.0f + p.boost * (1.0f - satNow));
    // The grey this desaturates towards cannot itself be negative. Y has a negative
    // blue coefficient in every wide gamut here, so a pixel sitting far outside the
    // destination has Y < 0 - and pulling all three channels towards a negative grey
    // sends every one of them below zero at once. The max then goes with them, and a
    // pixel with no positive channel has no achromatic for sm_gamut_compress to
    // measure against, so it comes through as it is. Measured before this line:
    // 593 negative pixels in 100000 random developments. It is the same defect that
    // was taken out of the tone stage, left behind here.
    //
    // A floor of zero, and not the power norm: the norm is far LARGER than Y on a
    // saturated colour (0.49 against 0.15 on a Rec.709 red), so desaturating towards
    // it would push the channels further out, not less. Every colour with Y >= 0 -
    // which is every colour inside the gamut - is untouched by this.
    float yl = SM_MAX(sm_to_xyz(o, outSpace).y, 0.0f);
    o = smf3(yl + (o.x - yl) * sf, yl + (o.y - yl) * sf, yl + (o.z - yl) * sf);

    // Last thing before the encode, on linear values, whichever branch we took:
    // whatever we are writing to, write something that can exist there. It runs on
    // the no-conversion branch too, because there the node's own space IS the one
    // being written, and a Rec.709 timeline can be pushed out of its gamut by the
    // white balance and saturation moves alone.
    o = sm_gamut_compress(o);
    return smf3(sm_encode(o.x, outGamma), sm_encode(o.y, outGamma), sm_encode(o.z, outGamma));
}

#ifndef __METAL_VERSION__
// ---------------------------------------------------------------- CPU only: white points

// Planckian locus (Kim et al. 2002), CIE 1931 xy
static inline void sm_planck_xy(double t, double* x, double* y) {
    t = t < 1667.0 ? 1667.0 : (t > 25000.0 ? 25000.0 : t);
    double it = 1000.0 / t, it2 = it * it, it3 = it2 * it;
    double xx = t <= 4000.0 ? -0.2661239 * it3 - 0.2343589 * it2 + 0.8776956 * it + 0.179910
                            : -3.0258469 * it3 + 2.1070379 * it2 + 0.2226347 * it + 0.240390;
    double x2 = xx * xx, x3 = x2 * xx;
    *y = t <= 2222.0 ? -1.1063814 * x3 - 1.34811020 * x2 + 2.18555832 * xx - 0.20219683
       : (t <= 4000.0 ? -0.9549476 * x3 - 1.37418593 * x2 + 2.09137015 * xx - 0.16748867
                      : 3.0817580 * x3 - 5.87338670 * x2 + 3.75112997 * xx - 0.37001483);
    *x = xx;
}
// White of an illuminant at temperature k with tint (positive = greener illuminant,
// so raising Tint makes the image more magenta), as XYZ with Y = 1.
// This has to be total: it is fed by numbers read out of a file, and a white point
// that is not a real colour produces NEGATIVE von Kries ratios, which is not a colour
// cast but a broken image - and one no setting of the slider can undo. So the tint is
// clamped to SM_TINT_LIMIT, and if the result still fails to be a physical white the
// point on the Planckian locus itself is returned: a real white, never a broken one.
static inline void sm_white_xyz(double k, double tint, double out[3]) {
    if (!(tint > -SM_TINT_LIMIT)) tint = -SM_TINT_LIMIT;       // also catches NaN
    else if (tint > SM_TINT_LIMIT) tint = SM_TINT_LIMIT;
    double x0, y0, x1, y1;
    sm_planck_xy(k, &x0, &y0);
    // The tint axis is the normal to the locus, so it needs a second point ON the
    // locus. sm_planck_xy clamps to 25000 K, so at the top of the range k * 1.01
    // lands on the same point, the tangent has length zero and the normal is 0/0.
    // Step the other way there. Both are clamped to the same range, so one of the
    // two always differs.
    double k1 = k * 1.01;
    sm_planck_xy(k1 > 25000.0 ? k / 1.01 : k1, &x1, &y1);
    double d0 = -2.0 * x0 + 12.0 * y0 + 3.0, d1 = -2.0 * x1 + 12.0 * y1 + 3.0;
    double u0 = 4.0 * x0 / d0, v0 = 6.0 * y0 / d0, u1 = 4.0 * x1 / d1, v1 = 6.0 * y1 / d1;
    double du = u1 - u0, dv = v1 - v0, len = sqrt(du * du + dv * dv);
    if (!(len > 0.0)) { out[0] = x0 / y0; out[1] = 1.0; out[2] = (1.0 - x0 - y0) / y0; return; }
    double nu = -dv / len, nv = du / len;
    if (nv < 0.0) { nu = -nu; nv = -nv; }
    double u = u0 + nu * tint / 3000.0, v = v0 + nv * tint / 3000.0;
    double d = 2.0 * u - 8.0 * v + 4.0;
    double x = d != 0.0 ? 3.0 * u / d : -1.0, y = d != 0.0 ? 2.0 * v / d : -1.0;
    if (!(y > 1e-6) || !(x > 0.0) || !(1.0 - x - y > 0.0)) { x = x0; y = y0; }
    out[0] = x / y; out[1] = 1.0; out[2] = (1.0 - x - y) / y;
}
static inline void sm_bradford(const double in[3], double out[3], int inverse) {
    const float* m = SM_BRADFORD + (inverse ? 9 : 0);
    for (int i = 0; i < 3; ++i)
        out[i] = m[i * 3] * in[0] + m[i * 3 + 1] * in[1] + m[i * 3 + 2] * in[2];
}
// A white whose CONE RESPONSES are positive. Staying inside the spectral locus is not
// enough: Tint +100 at 3200 K lands on XYZ (0.920, 1.000, 0.023), which is a colour,
// but its Bradford S comes out at -0.009 and the von Kries ratio built from it is
// -152 - one channel of the picture inverted, from two settings the sliders can
// reach. So the tint is walked back towards zero until the white is one the cones can
// represent. The control saturates instead of breaking, and only where it was asking
// for something that does not exist.
static const double SM_LMS_FLOOR = 0.02;   // of Y, which is 1 here by construction

static inline void sm_white_lms(double k, double tint, double lms[3]) {
    double xyz[3];
    for (int i = 0; i < 32; ++i) {
        sm_white_xyz(k, tint, xyz);
        sm_bradford(xyz, lms, 0);
        if (lms[0] > SM_LMS_FLOOR && lms[1] > SM_LMS_FLOOR && lms[2] > SM_LMS_FLOOR) return;
        tint *= 0.75;
    }
    sm_white_xyz(k, 0.0, xyz);
    sm_bradford(xyz, lms, 0);
}

// Fill the white-balance fields of DevelopParams from as-shot and chosen Kelvin/tint.
static inline void sm_set_white_balance(DevelopParams* p, double shotK, double shotTint, double k, double tint) {
    double ls[3], lt[3];
    sm_white_lms(shotK, shotTint, ls);
    sm_white_lms(k, tint, lt);
    double r[3] = { ls[0] / lt[0], ls[1] / lt[1], ls[2] / lt[2] };
    const double d65[3] = { 0.95046, 1.0, 1.08906 };
    double l65[3], lr[3], nw[3];
    sm_bradford(d65, l65, 0);
    for (int i = 0; i < 3; ++i) lr[i] = l65[i] * r[i];
    sm_bradford(lr, nw, 1);
    p->ratioL = (float)r[0];
    p->ratioM = (float)r[1];
    p->ratioS = (float)r[2];
    p->norm = nw[1] > 0.0 ? (float)(1.0 / nw[1]) : 1.0f;
}
#endif

#endif
