// SPDX-License-Identifier: GPL-3.0-or-later
#import <Metal/Metal.h>

#include <mutex>
#include <string>
#include <unordered_map>

#include "DevelopMath.h"
#include "DevelopMathSource.inc"  // kDevelopMathSource: DevelopMath.h as a string (generated by the Makefile)

static const char* kKernelSource =
    "kernel void SLogMetaRawKernel(constant int& p_Width [[buffer(11)]], constant int& p_Height [[buffer(12)]],\n"
    "                              constant DevelopParams& p_Params [[buffer(13)]],\n"
    "                              const device float* p_Input [[buffer(0)]], device float* p_Output [[buffer(8)]],\n"
    "                              uint2 id [[thread_position_in_grid]])\n"
    "{\n"
    "    if ((int)id.x < p_Width && (int)id.y < p_Height) {\n"
    "        const int i = ((int)id.y * p_Width + (int)id.x) * 4;\n"
    "        DevelopParams p = p_Params;\n"
    "        SMf3 o = sm_develop(smf3(p_Input[i], p_Input[i + 1], p_Input[i + 2]), p);\n"
    "        p_Output[i] = o.x; p_Output[i + 1] = o.y; p_Output[i + 2] = o.z;\n"
    "        p_Output[i + 3] = p_Input[i + 3];\n"
    "    }\n"
    "}\n";

static std::mutex s_PipelineMutex;
static std::unordered_map<id<MTLCommandQueue>, id<MTLComputePipelineState>> s_Pipelines;

bool RunMetalKernel(void* p_CmdQ, int p_Width, int p_Height, const DevelopParams& p_Params, const float* p_Input, float* p_Output)
{
    id<MTLCommandQueue> queue = static_cast<id<MTLCommandQueue>>(p_CmdQ);
    id<MTLDevice> device = queue.device;
    id<MTLComputePipelineState> pipelineState = nil;
    {
        std::unique_lock<std::mutex> lock(s_PipelineMutex);
        auto it = s_Pipelines.find(queue);
        if (it == s_Pipelines.end()) {
            NSError* err = nil;
            std::string source = std::string("#include <metal_stdlib>\nusing namespace metal;\n")
                               + kDevelopMathSource + "\n" + kKernelSource;
            MTLCompileOptions* options = [MTLCompileOptions new];
            // keep log/pow precise: results must match the CPU path
            if (@available(macOS 15.0, *)) {
                options.mathMode = MTLMathModeSafe;
            } else {
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
                options.fastMathEnabled = NO;
#pragma clang diagnostic pop
            }
            id<MTLLibrary> library = [device newLibraryWithSource:@(source.c_str()) options:options error:&err];
            [options release];
            if (!library) {
                fprintf(stderr, "SLogMetaRaw: failed to compile Metal kernel: %s\n", err.localizedDescription.UTF8String);
                return false;
            }
            id<MTLFunction> function = [library newFunctionWithName:@"SLogMetaRawKernel"];
            pipelineState = function ? [device newComputePipelineStateWithFunction:function error:&err] : nil;
            [function release];
            [library release];
            if (!pipelineState) {
                fprintf(stderr, "SLogMetaRaw: failed to create Metal pipeline\n");
                return false;
            }
            s_Pipelines[queue] = pipelineState;
        } else {
            pipelineState = it->second;
        }
    }

    id<MTLBuffer> srcBuf = reinterpret_cast<id<MTLBuffer>>(const_cast<float*>(p_Input));
    id<MTLBuffer> dstBuf = reinterpret_cast<id<MTLBuffer>>(p_Output);
    id<MTLCommandBuffer> commandBuffer = [queue commandBuffer];
    commandBuffer.label = @"SLogMetaRawKernel";
    id<MTLComputeCommandEncoder> encoder = [commandBuffer computeCommandEncoder];
    [encoder setComputePipelineState:pipelineState];

    const NSUInteger exeWidth = [pipelineState threadExecutionWidth];
    MTLSize threadsPerGroup = MTLSizeMake(exeWidth, 1, 1);
    MTLSize groups = MTLSizeMake((p_Width + exeWidth - 1) / exeWidth, p_Height, 1);

    [encoder setBuffer:srcBuf offset:0 atIndex:0];
    [encoder setBuffer:dstBuf offset:0 atIndex:8];
    [encoder setBytes:&p_Width length:sizeof(int) atIndex:11];
    [encoder setBytes:&p_Height length:sizeof(int) atIndex:12];
    [encoder setBytes:&p_Params length:sizeof(DevelopParams) atIndex:13];
    [encoder dispatchThreadgroups:groups threadsPerThreadgroup:threadsPerGroup];
    [encoder endEncoding];
    [commandBuffer commit];
    return true;
}
