# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate ofx/SLogMetaRaw/gen/: the gamut matrices, one DevelopMath.h built from math/*.h, and the
Metal sources as C strings (the kernels are compiled at runtime, from text).

Each math module is a valid header on its own; here they are concatenated in MODULES order with
their internal includes removed, so C++ and Metal compile exactly the same text.
"""
import os
import re
import sys

from gamut_matrices import matrices

HERE = os.path.dirname(os.path.abspath(__file__))
OFX_DIR = os.path.join(os.path.dirname(HERE), 'ofx', 'SLogMetaRaw')
GEN = os.path.join(OFX_DIR, 'gen')

MODULES = ['math/Common.h', 'math/Params.h', 'math/Transfer.h', 'gen/GamutMatrices.h', 'math/Gamut.h',
           'math/Levels.h', 'math/Tone.h', 'math/Color.h', 'math/FalseColor.h', 'math/Develop.h',
           'math/Detail.h', 'math/HostOnly.h', 'math/ToneHost.h', 'math/DetailHost.h']
KERNELS = [('kMetalDevelop', 'metal/kernels/Develop.metal'), ('kMetalDetail', 'metal/kernels/Detail.metal')]
# Metal contracts a*b+c into an FMA by default and the CPU build does not: parity needs it off.
PRELUDE = '#include <metal_stdlib>\nusing namespace metal;\n#pragma STDC FP_CONTRACT OFF\n'

INCLUDE = re.compile(r'^\s*#\s*include\s+"([^"]+)"\s*$')


def f(v):
    """Float literal valid in C++ and Metal: always has a decimal point ('0.0f', never '0f')."""
    s = ('%.9f' % v).rstrip('0')
    if s.endswith('.'):
        s += '0'
    if s in ('-0.0', '0.0'):
        s = '0.0'
    return s + 'f'


def c_array(name, idx):
    rows = []
    for code, (sp, m, mi) in enumerate(matrices()):
        mat = m if idx == 0 else mi
        rows.append('    ' + ', '.join(f(v) for r in mat for v in r) + ',  // %d %s' % (code, sp))
    return 'SM_CONST float %s[%d] = {\n%s\n};' % (name, 9 * len(rows), '\n'.join(rows))


def gamut_header():
    return ('// GENERATED by tools/build_math.py from tools/gamut_matrices.py - do not edit.\n'
            '#pragma once\n#include "../math/Common.h"\n\n'
            + c_array('SM_RGB_TO_XYZ', 0) + '\n' + c_array('SM_XYZ_TO_RGB', 1) + '\n')


def amalgamate(texts):
    """Concatenate the modules, dropping #pragma once and includes of modules already emitted."""
    emitted, out = set(), []
    for rel in MODULES:
        body = []
        for line in texts[rel].splitlines():
            if line.strip() == '#pragma once':
                continue
            m = INCLUDE.match(line)
            if m:
                target = os.path.normpath(os.path.join(os.path.dirname(rel), m.group(1)))
                if target not in emitted:
                    sys.exit('build_math: %s includes %s, which is not emitted before it' % (rel, target))
                continue
            body.append(line)
        emitted.add(rel)
        out.append('// ---- %s\n%s' % (rel, '\n'.join(body).strip('\n')))
    return ('// GENERATED by tools/build_math.py from ofx/SLogMetaRaw/math - do not edit.\n'
            '#ifndef SLOGMETARAW_DEVELOP_MATH_H\n#define SLOGMETARAW_DEVELOP_MATH_H\n\n'
            + '\n\n'.join(out) + '\n\n#endif\n')


def c_string(name, text):
    lines = ['static const char* %s =' % name]
    for line in text.splitlines():
        lines.append('    "%s\\n"' % line.replace('\\', '\\\\').replace('"', '\\"'))
    lines[-1] += ';'
    return '\n'.join(lines) + '\n'


def write_if_changed(path, text):
    try:
        with open(path, encoding='utf-8') as fh:
            if fh.read() == text:
                return False
    except OSError:
        pass
    with open(path, 'w', encoding='utf-8') as fh:
        fh.write(text)
    return True


def main():
    os.makedirs(GEN, exist_ok=True)
    texts = {'gen/GamutMatrices.h': gamut_header()}
    for rel in MODULES:
        if rel not in texts:
            with open(os.path.join(OFX_DIR, rel), encoding='utf-8') as fh:
                texts[rel] = fh.read()
    math = amalgamate(texts)
    metal = c_string('kMetalPrelude', PRELUDE + math)
    for name, rel in KERNELS:
        with open(os.path.join(OFX_DIR, rel), encoding='utf-8') as fh:
            metal += c_string(name, fh.read())
    for rel, text in (('gen/GamutMatrices.h', texts['gen/GamutMatrices.h']), ('gen/DevelopMath.h', math),
                      ('gen/MetalSource.inc', '// GENERATED by tools/build_math.py - do not edit.\n' + metal)):
        if write_if_changed(os.path.join(OFX_DIR, rel), text):
            print('written', rel)


if __name__ == '__main__':
    main()
